### ISSUE TITLE
where is kafka-avro-console-producer?

### ISSUE THREAD

**Issue by Tracy6465** [confluentinc/kafka-connect-hdfs#110]
I can't find the kafka-avro-console-producer file in the kafaka/bin folder!

**Comment by Tracy6465** [comment]
I import the maven project in eclipse,and compile the source file  to jar file ,now ,I don't know  how to use the jar file between kafka and hadoop

**Comment by ewencp** [comment]
`kafka-avro-console-producer` is not part of Kafka. It is an extra utility provided in [Confluent Platform](http://www.confluent.io/download) which is similar to the built-in `kafka-console-producer` but has some preset options for integration with the [Schema Registry](http://docs.confluent.io/3.0.0/schema-registry/docs/index.html) and the serializers included with it. You can find the source for it in the [schema registry repository](https://github.com/confluentinc/schema-registry/blob/master/bin/kafka-avro-console-consumer) but to actually run it you probably just want to download Confluent Platform and use the version included there.
