### ISSUE TITLE
Connector Doesn't Polling Automatically

### ISSUE THREAD

**Issue by iceNuts** [confluentinc/kafka-connect-hdfs#123]
Hi there,

I meet an issue that:

hdfs connector start reading from topic and write to hive table for example first 20 rows (assume we have 50 rows in total) then it will stop. When I insert a new row, it may read another 5 rows, and stop again. It won't read 50 rows if there wasn't any new rows add to the topic. It looks hdfs connector stops auto polling.

Is there anyone could help?

Thanks

**Comment by lakeofsand** [comment]
maybe this：
https://github.com/confluentinc/kafka-connect-hdfs/issues/79

**Comment by iceNuts** [comment]
@lakeofsand Thanks a lot, I think it might be the same issue. By the way, is there any workaround you know?

**Comment by lakeofsand** [comment]
https://github.com/confluentinc/kafka-connect-hdfs/pull/100/commits
seems like this PR has  not been accepted.

**Comment by cotedm** [comment]
Closing this as #100 was merged and should address this.
