### ISSUE TITLE
Fix topics with periods for hive

### ISSUE THREAD

**Issue by ig-michaelpearce** [confluentinc/kafka-connect-hdfs#136]
Whilst "Fix handling of topics with periods " [70](https://github.com/confluentinc/kafka-connect-hdfs/pull/70) fixes HDFS ingestion we still get issue when enabling hive as dots cannot be used in a table name.

**Comment by cotedm** [comment]
@ig-michaelpearce you shouldn't use `.` in your topic names per the warning we throw when you create a topic name with `.` but can you confirm that table names with `.` are valid in Hive? Last I knew, only coulmn names support `.` in the string.

**Comment by cotedm** [comment]
Actually, I'm going to close this as a duplicate as #155 is probably the right way to go here.

**Comment by ig-michaelpearce** [comment]
@cotedm "." cannot be used in table names, thus the issue. the "." notation is used to separate db/schema/table in sql world.

**Comment by cotedm** [comment]
Ah sorry, I didn't understand what you meant, but it's more clear after seeing PR #137. I think it makes sense to do the replace of "." with "_" for the table names and then #155 is a separate issue altogether as this is a very specific case. I'll mark this as a bug that is closed by #137 being merged (when that happens).

**Comment by ig-michaelpearce** [comment]
@cotedm Who could merge it? As its been waiting since Oct already.

**Comment by cotedm** [comment]
@ig-michaelpearce I'll see what I can do about getting it merged. I did a review today and I just see some mistaken imports and it'd be good if we can have a unit test to make sure the replacement doesn't have an accidental regression with someone else's changes in the future IMO. If you can make those two updates, that will grease the wheels on getting it merged most likely.

**Comment by ig-michaelpearce** [comment]
@cotedm because this has been open so long, i think we've accidentally re-forked in November thus the source shows now unknown repository. Any idea's how i can either get this back? If not can this be merged, and then i can re-fork, and commit to address those bits ASAP? Say latest Friday?

**Comment by cotedm** [comment]
@ig-michaelpearce sorry about the time for the review. I'm not sure how you can get the repo back. I think a new PR with the changes is the cleanest option if you could do that. When I see the new PR I'll try to get it reviewed as quickly as possible for you.

**Comment by ig-michaelpearce** [comment]
@cotedm ok lets go with that route, ill try get it all done by latest Friday

**Comment by ig-michaelpearce** [comment]
@cotedm as discussed new PR with review changes due to deleted/re-forked local repo - #164

**Comment by cotedm** [comment]
Thanks @ig-michaelpearce. It looks good to me, but I pinged a second reviewer just in case I missed anything. If he gives a 👍 we'll go ahead and merge it. Thanks for your patience on this one :)

**Comment by cotedm** [comment]
thanks @ig-michaelpearce ! This has now been merged.
