### ISSUE TITLE
Fail to build project through maven

### ISSUE THREAD

**Issue by apenkava** [confluentinc/kafka-connect-hdfs#138]
I am unable to build the project with the included pom.xml file. The required artifacts are not available, and since the confluent maven repo is not browsable, it is hard to find the correct artifacts. I tried both master and 3.1.x release with the same result.

mvn clean install -U 

> Failed to execute goal on project kafka-connect-hdfs: Could not resolve dependencies for project io.confluent:kafka-connect-hdfs:jar:3.2.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:connect-api:jar:0.10.2.0-SNAPSHOT, io.confluent:kafka-connect-avro-converter:jar:3.2.0-SNAPSHOT: Could not find artifact org.apache.kafka:connect-api:jar:0.10.2.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/) -> [Help 1]

**Comment by ewencp** [comment]
Development branches sometimes have SNAPSHOT dependencies which are not published to Maven currently. See [this FAQ entry](https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ#when-i-try-to-compile-i-get-an-error-about-a-missing-snapshot-dependency)

**Comment by apenkava** [comment]
Thanks for the quick reply. So if don't want to build all the missing dependencies, it seems I need to go with 3.0.1 tag.

Ales

**Comment by apenkava** [comment]
Successfully built from 3.0.1 tag
