### ISSUE TITLE
TimeBasedPartitionerTest.testGeneratePartitionedPath fails on spanish MacOS

### ISSUE THREAD

**Issue by rossoft** [confluentinc/kafka-connect-hdfs#140]
TimeBasedPartitionerTest.testGeneratePartitionedPath fails on a spanish MacOS with the following error:

  TimeBasedPartitionerTest.testGeneratePartitionedPath:42 expected:<...pic/year=2015/month=[January]/day=01/hour=2/> but was:<...pic/year=2015/month=[enero]/day=01/hour=2/>

The month name seems to be depending on user locale, rather than always english

**Comment by ewencp** [comment]
Resolved in master by #214
