### ISSUE TITLE
hdfs-site.xml and core-site.xml with kafka-connect inside Docker

### ISSUE THREAD

**Issue by zborisha** [confluentinc/kafka-connect-hdfs#147]
We are running kafka-connect inside Docker and we run HDFS in HA mode. 
Are there any guidelines how to use hdfs-site.xml and core-site.xml in this case? We can not simply specify hdfs.url to kafka-connect - HDFS is running in HA mode so namenode might change... 

thanks

**Comment by lakeofsand** [comment]
@zborisha 
Does your  HDFS cluster run in Docker?
If not，you can use keepalived+namenode，and configure connector hdfs.url use the virtual ip.

**Comment by zborisha** [comment]
@lakeofsand thanks

Well we run everything on DCOS actually - confluent platform + HDFS ... I will take a look if keepalived can help us... I just wanted to check if kafka-connect has a solution for this

**Comment by cotedm** [comment]
@zborisha you should be able to add the hdfs-site.xml and core-site.xml to the classpath with docker in a way similar to what is described [here](http://docs.confluent.io/3.1.1/cp-docker-images/docs/operations/external-volumes.html#configuring-connect-with-external-jars). The other option that @lakeofsand mentioned should also work. This is more of a docker operations thing than a kafka-connect thing, so I will close it now. If you find that something is missing from the implementation of this connector that won't let you use it from a docker container, we're happy to address it.

**Comment by lakeofsand** [comment]
We change our deploy to the method @cotedm mentioned recently, **it works**, only need to add he hdfs-site.xml and core-site.xml to the classpath,and add property like below.
<property>
      <name>dfs.client.failover.proxy.provider._yourname_</name>
      <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
</property>

We have been misguided by the below issue a lot before.
https://github.com/confluentinc/kafka-connect-hdfs/issues/76  


The 'virtual ip' method had two disadvantage:
a、keepalived is not so reliable
b、When implement in docker，keepalived is not suitable.
