### ISSUE TITLE
kafka Hdfs connect not flushing the data from +tmp to actual topic hdfs file system 

### ISSUE THREAD

**Issue by madhu231** [confluentinc/kafka-connect-hdfs#148]
![hdfs_2](https://cloud.githubusercontent.com/assets/12507635/20050070/1eb5055c-a4ed-11e6-9e39-02714ac6d9bd.PNG)
![hdfs_1](https://cloud.githubusercontent.com/assets/12507635/20050122/69562384-a4ed-11e6-8f5b-698ede79b518.PNG)

[kafka_connect_hdfs_console_log.txt](https://github.com/confluentinc/kafka-connect-hdfs/files/574718/kafka_connect_hdfs_console_log.txt)

- Kafka Hdfs connect sink process stuck and not flushing the data  from `+tmp` to actual topic hdfs file system. I have attached my kafka connect hdfs sink configuration

@ewencp please can you help us to resolve this issue.

**Comment by madhu231** [comment]
@bijums please go thorugh this

**Comment by lakeofsand** [comment]
can see any exception in connect.log?

**Comment by madhu231** [comment]
@lakeofsand thank you for replaying on this... where " connect.log " is located?

**Comment by lakeofsand** [comment]
@madhu231  see your connect process:
ps -aux | grep ConnectDistributed
-Dkafka.logs.dir=xxx

**Comment by nivemaham** [comment]
I am facing the same issue. I would like to know why this is happening? Is it due to huge flush.size? 
How can i resolve this?

**Comment by heifrank** [comment]
@madhu231 
I'm facing the same issue, have you solve the problem yet?

My configuration is:
name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=test_hdfs4
#topics=test_hdfs_kafka
hdfs.url=hdfs://10.103.18.9:9000
flush.size=3


partitioner.class=io.confluent.connect.hdfs.partitioner.FieldPartitioner
partition.field.name=f1

**Comment by NishantVerma07** [comment]
I am facing a similar situation.

Did anyone find solution to this?

My controller.log reads below:

[2017-01-13 01:02:45,884] DEBUG [Controller 1]: topics not in preferred replica Map() (kafka.controller.KafkaController)
[2017-01-13 01:02:45,884] TRACE [Controller 1]: leader imbalance ratio for broker 1 is 0.000000 (kafka.controller.KafkaController)
[2017-01-13 01:02:45,884] DEBUG [Controller 1]: topics not in preferred replica Map() (kafka.controller.KafkaController)
[2017-01-13 01:02:45,884] TRACE [Controller 1]: leader imbalance ratio for broker 0 is 0.000000 (kafka.controller.KafkaController)
[2017-01-13 01:07:45,883] TRACE [Controller 1]: checking need to trigger partition rebalance (kafka.controller.KafkaController)


No exception

**Comment by nivemaham** [comment]
Hi there, in my case it turned out that messages are written to +tmp folder until the flush size is met, or when the connector is disconnected before the committed offsets are written to topic directory. This happened when there weren't enough messages to consume on the topic queue when the flush size was larger. If you have hdfs-connector as a long running service, eventually when criteria are met, the file is written to topic dir.

**Comment by cotedm** [comment]
@madhu231 it's important to note here that `flush.size` is the number of records needed to come into the WAL before the file will be moved from tmp and committed to the final directory. You've set this to 4096 but the size in your screenshot is only 0.1KB implying you don't have many records sent yet. You can lower `flush.size` or you can send more records to get it to roll. 

There are actually a few different issues opened for "WAL isn't rolling" in the repo with different causes. This one appears to be that misconfig, so I will close it. Addressing the other ones in other issues will help clear up the symptoms and causes so I'm taking that approach here. If that doesn't work for you @madhu231 then please let us know.

**Comment by FengJinghHua** [comment]
@madhu231 do you try to use the connector **rotate.interval.ms**?

**Comment by madhu231** [comment]
@FengJinghHua issue is resolved as @cotedm said changed the flush size and it worked. thanks

**Comment by FengJinghHua** [comment]
@madhu231 congratulation, but if ‘your data sometimes are huge，you can use config **rotate.schedule.interval.ms**   as a timer, be  more flexible suitable for data size and transmission frequency， you can find the discussion in here [](https://github.com/confluentinc/kafka-connect-storage-cloud/issues/27)

**Comment by FengJinghHua** [comment]
@madhu231 congratulation, but if ‘your data sometimes are huge，you can use config rotate.schedule.interval.ms as a timer, be more flexible suitable for data size and transmission frequency， you can find the discussion in here https://github.com/confluentinc/kafka-connect-storage-cloud/issues/27
