### ISSUE TITLE
Ignoring stale out-of-order record

### ISSUE THREAD

**Issue by krisskross** [confluentinc/kafka-connect-hdfs#158]
Hi

We have a very aggressive retention period on one of our topic. Sometimes Kafka-Connect falls behind and fail to index the before its cleaned up by Kafka. It's OK for this particular topic to fall behind and loose messages this way. But it seems that the connector never recovers from this state, no messages are put in HDFS after this fact.

This is the error which is logged.

[2016-12-05 15:24:26,389] INFO Ignoring stale out-of-order record in topic-2. Has offset 2042206669 instead of expected offset 2039744107 (io.confluent.connect.hdfs.TopicPartitionWriter:518)

The only way we found to recover from this state is to swipe all data in the topic, logs and +tmp directory and start fresh. Is there a better way?

Cheers,
-Kristoffer

**Comment by savulchik** [comment]
@krisskross see issue https://github.com/confluentinc/kafka-connect-hdfs/issues/132

**Comment by krisskross** [comment]
Thanks @savulchik
