### ISSUE TITLE
what is the different between connect-api 0.9.0.0-cp1 vs 0.9.0.0

### ISSUE THREAD

**Issue by lakeofsand** [confluentinc/kafka-connect-hdfs#160]
when we build kafka-connect-hdfs，there come out with:
"The POM for org.apache.kafka:connect-api:jar:0.9.0.0-cp1 is missing, no dependency information available"

found that in many maven repo, there are only 0.9.0.0 or 0.9.0.1.

See back in github(https://github.com/confluentinc/kafka/releases),also no 0.9.0.0-cp1.

Can i switch the dependecy from 0.9.0.0-cp1 to 0.9.0.1?

**Comment by cotedm** [comment]
@lakeofsand yes that should be fine if it works for you. We've settled on a more structured release process lately to make this easier so after 3.0, the pom.xml should work just fine out of the box. Our builds of Kafka end in -cp1 for the version but there may have been some inconsistency there in the older releases (pre 3.0).
