### ISSUE TITLE
Hdfs connector not flushing data from +tmp to hdfs topics directory

### ISSUE THREAD

**Issue by heifrank** [confluentinc/kafka-connect-hdfs#161]
Hi, all 
      I'm using hdfs connector but meet a problem that the data stored in +tmp are not flushed to actual hdfs topics path. The configuration of hdfs.properties is as follows:

name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=test_hdfs4
#topics=test_hdfs_kafka
hdfs.url=hdfs://10.103.18.9:9000
flush.size=3
partitioner.class=io.confluent.connect.hdfs.partitioner.FieldPartitioner
partition.field.name=f1

Can someone give any suggestions?

**Comment by cotedm** [comment]
@heifrank can you provide some more information? Are you sure you are sending at least 3 records to a single partition where f1 is the same to trigger the roll? If you set `rotate.interval.ms` and `rotate.schedule.interval.ms` do you have success? What version are you using? Do you have anything in the worker logs that looks suspicious?

**Comment by levzem** [comment]
closing this due to no response. feel free to reopen if there is still an issue
