### ISSUE TITLE
Data not written in HDFS

### ISSUE THREAD

**Issue by NishantVerma07** [confluentinc/kafka-connect-hdfs#163]
1- I have a KAFKA standalone setup.
2- I have one HDFS cluster setup.
3- Both are independent of each other i.e., KAFKA is running on IP - 10.16.34.57 and HDFS cluster has 10.16.37.124(Master Node), 10.16.37.32(Data Node 1) and 10.16.37.61(Data Node 2).
4- These 4 servers are able to communicate with one another
5- I downloaded confluent-2.0 on 10.16.34.57 where KAFKA is running.
6- I stopped the already running KAFKA and ZOOKEEPER services and started the KAFKA and ZOOKEEPER from inside CONFLUENT. (Hope this step is OK)
7- My quickstart-hdfs.properties  has hdfs.url=hdfs://ip-10-16-37-124:9000 (the master node hostname and port)
8- Started Schema Registry. 
9- Created one AVRO CONSOLE producer and entered
{"f1": "value1"}
{"f1": "value2"}
{"f1": "value3"}
10- Started HDFS CONNECTOR.
11- No error as of now. But the file is not written in HDFS. tmp directory is created though but it is empty.

What could be the reason here?

When I did the CONFLUENT, KAFKA and ZOOKEEPER setup in 10.16.37.124(The master node of HDFS cluster), then everything works OK. Data is written into HDFS.

**Comment by cotedm** [comment]
@NishantVerma07 I'm not sure I understand step 6 above. Are you saying you are running a different Kafka and ZooKeeper version with the same data directories? Probably this is the step that is causing the problem and data is not properly making it to Kafka. You should check with the console consumer that the data you are expecting actually made it to Kafka. For reference, the [migration guide](http://docs.confluent.io/3.1.1/installation.html#migrating-from-confluent-open-source-to-confluent-enterprise) can help you with caveats for going from Apache Kafka to the Confluent version. That said, if it's working when you run it on the HDFS NameNode, then this connector is likely working. If you still have trouble, I suggest you ask your questions on migration on the [mailing list](https://groups.google.com/forum/#!forum/confluent-platform) as it's more about general Kafka than this connector.
