### ISSUE TITLE
Make WAL Storage as a configurable option

### ISSUE THREAD

**Issue by alunarbeach** [confluentinc/kafka-connect-hdfs#169]
WALs are stored in HDFS storage currently. This is good for HDFS File System that supports the append operation. When you use object stores (Google Storage, S3, azure) that do not support the append operation, HDFS Sink throws errors stating append operation not supported. Please make WAL as a configurable option

**Comment by cotedm** [comment]
@alunarbeach this is a bit out of scope. This connector is for writing specifically to HDFS and not generically to all storage backends. connectors.confluent.io has links to other connectors that can help you with those other types of storage that have their own semantics.

**Comment by alunarbeach** [comment]
@cotedm Just to be sure, my case is understood well. I am asking to add a configuration option wal.class similar to storage.class and configurations that can be passed to WAL
By default, it's using the FSWAL which is instantiated from wal method in storage class.
https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/storage/HdfsStorage.java#L88

I am able to extend the storage class and define another WAL class (reusing in-memory WAL from the test package) and it's working fine. 
if needed, I can make a pull request.

**Comment by alunarbeach** [comment]
@cotedm Just a reminder.
