### ISSUE TITLE
Kafka HDFS connect, does it work with HDFS (SSL)

### ISSUE THREAD

**Issue by bharatviswa504** [confluentinc/kafka-connect-hdfs#171]
Hi,
Does Kafka HDFS Connect work with HDFS (SSL). As I see only properties in security is 
hdfs.authentication.kerberos, connect.hdfs.keytab,hdfs.namenode.principal as these properties are all related to HDFS Kerberos.

As from the configuration and code I see we pass only Kerberos parameters, not seen SSL configuration, so want to confirm will the Kafka HDFS Connector works with HDFS (SSL enabled)?

**Comment by bharatviswa504** [comment]
I think it should work, as the configuration is passed through hadoop.conf.dir which is required for SSL.

**Comment by cotedm** [comment]
@bharatviswa504 it should work, the configuration for the HDFS client embedded in the connector should be transparent with `hadoop.conf.dir` as you mentioned.
