### ISSUE TITLE
ORC Format to HDFS

### ISSUE THREAD

**Issue by RussWinkler** [confluentinc/kafka-connect-hdfs#173]
Are there any plans for an ORCFormat (like Parquet and Avro Format) that can be used with the connector to write out Avro Schema styled data into HDFS in ORC format?

**Comment by cotedm** [comment]
@RussWinkler there's no one working on this that I'm aware of right now. The format is pluggable, so you could write one yourself and a contribution of such a format would be useful. Did you want to make a run at implementing one? It would require you to implement the [Format](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/Format.java) as has been done for [Avro](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/avro/AvroFormat.java) and [Parquet](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/parquet/ParquetFormat.java) already.

**Comment by RussWinkler** [comment]
I figured that was probably the case and yes, I would be interested in developing one.  I have already looked into it some and already have some skeleton classes for the ORC format based on the Parquet and Avro ones in a local branch.

**Comment by cotedm** [comment]
@RussWinkler awesome! If you submit a pull request for it, we would be happy to take a look.

**Comment by RussWinkler** [comment]
I've finished the ORC Format and initial testing looks good.  I'm having a problem duplicating some of the Avro/Parquet tests (and running current Avro or Parquet tests) that use the MiniDFSCluster.  The tests are timing out waiting for the mini cluster to become active.  Is there a secret to get these tests running locally?

**Comment by StefanPapp** [comment]
What is the status on this? I also need this feature and I consider to implement it myself if it is not done yet.

**Comment by RussWinkler** [comment]
I was able to partially implement the ORC Format but there are some limitations to my implementation.  Because I used the ORC TypeDescription it doesn't support versioning so the Hive Integration doesn't work with the connector.  I also rolled my own simple converstion from Avro to ORC that only supports primitives and a few simple structs, so it's nowhere near as robust as the Parquet Format for what it can handle. I did some testing and a simple connector works, but I have not tested it extensively and have got sidetracked recently.  You can check out what I do have synced up to this point at https://github.com/RussWinkler/OrcFormat.

**Comment by RussWinkler** [comment]
I've had some time recently to look into this again, and it seems that the biggest blocker for allowing Hive integration is that the current Apache ORC writer (OrcFile.createWriter) implementation doesn't seem to support any schema version, but the Hive table metadata does.  Does anyone know of a way to access the metadata of a table directly using java so I can add the schema version to it?

**Comment by ewencp** [comment]
@RussWinkler Not sure I understand the issue. iirc, for Avro the HIve integration doesn't need versions, it uses the schema in the file to decode and then Hive can project as necessary to the current table schema. I don't think we ever store/use version information explicitly. My understanding was that ORC is self-describing wrt the schema, so I thought the same thing would work for it?

**Comment by RussWinkler** [comment]
Thanks for the reply @ewencp, Looking through the ParquetFormat, Parquet picks up the schema version number from Avro and is able to write that out to the hive metadata.  The OrcFile utility and associated writer (and ORC in general) don't care about the schema version.  ORC can describe the table structure in it's TypeDescription "schema" but without a version number it can't support schema changes.  Without having a schema version number in there I get an exception when hive integration is turned on because it checks for that schema version.  

It seems that to be able to support ORC *and* hive integration, we need to wrap the current ORC writer with some hadoop/hive support to add the schema version and be able to alter the table in the appropriate way whenever there is a version change, similar to how the ParquetFormat does with it's InternalParquetWriter/Reader.  This second part I am just getting into, but it seems Hive only marginally supports ORC schema structure changes anyway.

**Comment by ewencp** [comment]
@RussWinkler Is it possible it depends on the version of Hive? https://community.hortonworks.com/questions/26718/orc-schema-evolution-in-hive.html suggests schema evolution support was added between 1.2 and 2.2 and incrementally.

**Comment by RussWinkler** [comment]
It does yeah.  That's the same question I read earlier.  It sounds like Parquet has more support than ORC but it's enough to work with.  I'm not as familiar with modifying Hive metadata in java though, is there a plugin or utility that will let me access and update the metadata with the version number?

**Comment by ewencp** [comment]
@RussWinkler I'm not aware of one, but I'm only very roughly familiar with Hive's APIs too. We can ping @gwenshap @cotedm who know more about hadoop/hive than I do, and maybe @cmccabe as a long shot just because I know he knows the hadoop ecosystem even if he hasn't done much with Connect.

**Comment by levzem** [comment]
#484 was just merged, adding ORC format to HDFS, thus closing this. This will be available around the next CP release with a new version of the connector
