### ISSUE TITLE
Add Avro compression codec support

### ISSUE THREAD

**Issue by westerly** [confluentinc/kafka-connect-hdfs#174]
Hi all,

It would be nice to be able to configure the hdfs connector to be able to compress data synced into the Avro format. The different compression codec supported by Avro are "deflate" and "snappy".

**Comment by cotedm** [comment]
@westerly certainly seems possible at first glance even though I'm not that familiar with the Avro compression concepts. Did you want to make an attempt at a pull request? It seems like you would need to be able to specify an additional configuration for the AvroFormat (and `AvroRecordWriterProvider`) then use `DataFileWriter.setCodec`. There would need to be some tests written here for config validation and to verify the compressed files are readable.

**Comment by NishanthShajahan** [comment]
Hi All,
How can I enable  compression  when connectors are configured through confluent control center?

**Comment by rhauch** [comment]
@NishanthShajahan what version of Confluent Control Center are you using? IIUC, version 4.0 of Control Center and the connector both have fixes that make this possible.

**Comment by NishanthShajahan** [comment]
I am using 4.0 of control center . I am not seeing anything on the  UI that
lets me specify the compression codec. unless I am missing something.

**Comment by kkonstantine** [comment]
@NishanthShajahan the feature has been merged and will be available in Confluent 4.1 
(related PR here: https://github.com/confluentinc/kafka-connect-hdfs/pull/255) 

In Confluent Control Center the option to select the compression codec will appear within the group _Connector_ and will be available if you select `AvroFormat` in `format.class`. Available options will be: `null, deflate, snappy,` or `bzip2`

Given that this has been merged, I'm closing this issue.
