### ISSUE TITLE
connector pause doesn't work

### ISSUE THREAD

**Issue by lijubjohn** [confluentinc/kafka-connect-hdfs#181]
kafka-connect-hdfs pause api doesn’t work as expected , it pauses all the partitions but resumes them after sometime, this seems to be because in TopicPartitionWriter , it resumes paused partition when buffer is empty

https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java#L330-L350

**Comment by yudong2015** [comment]
Hi @lijubjohn, How do you handle this problem?
