### ISSUE TITLE
How to ensure the efficiency of writing HDFS？

### ISSUE THREAD

**Issue by imperio-wxm** [confluentinc/kafka-connect-hdfs#193]
I read the source and there is a problem confusing me.

```java
// TopicPartitionWriter.java—>write()

while (!buffer.isEmpty()) {
    ......
    // just one message
    buffer.peek();
    writeRecord(projectedRecord);
    writer.write(record);
    ......
    avrowriter.append(record);
    ......
}
```

Yes, Buffer the data with buffer. In fact one by one to write to hdfs.
This will affect the efficiency of writing hdfs？Such as too much connection, open the file too much or  i/o bottleneck？Does the frequent write file affect the cluster?

How about this？

```java
while (!buffer.isEmpty()) {
    ......
    // Write all at once and change data to string with schema
   StringBuilder string = new StringBuilder();
   for(String str : buffer) {
       string.append(str).append("\n");
    }
    writer.write(string.tostring());
    // clear buffer
    ......
}
```
If so, is it more efficient? And how to ensure 'Exactly Once Delivery'?

**Comment by levzem** [comment]
The connector ensures EO delivery by using a WriteAheadLog.
https://docs.confluent.io/current/connect/kafka-connect-hdfs/index.html#features

feel free to reopen if you have any further questions
