### ISSUE TITLE
Mapping kafka message attributes as hive table attributes

### ISSUE THREAD

**Issue by patrikni** [confluentinc/kafka-connect-hdfs#195]
I have a Kafka HDFS/Hive sink connector targeted directy to Hive table (Avro format). In the Hive table I need kafka message attributes like partition id, message offset and message time (message time type). 

Is there any posibility to add such attributes to the message data?

**Comment by cricket007** [comment]
@patrikni Have you tried using the [Kafka Connect Transformations to insert this data](http://kafka.apache.org/documentation/#connect_transforms)? 

The Message Time can be applied via a `TimeBasedPartitioner` and using the `Record` time extractor. It will land in HDFS as a separate directory, which is seen as a column in the Hive table.

**Comment by patrikni** [comment]
Thanks @cricket007. I am still on Kafka Connect which does not support Transformation. Nevertheless it is good idea I will use connect upgdade.

**Comment by cricket007** [comment]
Hmm. Sorry I didn't reply sooner.

AFAIK, Connect transforms existed in the one of the first versions of Connect

https://cwiki.apache.org/confluence/display/KAFKA/KIP-66%3A+Single+Message+Transforms+for+Kafka+Connect

**Comment by kkonstantine** [comment]
Transformations appeared little after Connect was introduced, in a few versions down the road. They have been around since 0.10.2 for a little less than two years now. I'd agree they fit in this use case nicely.
