### ISSUE TITLE
Not write to offset.storage.file.filename file for standalone mode

### ISSUE THREAD

**Issue by shuhanding** [confluentinc/kafka-connect-hdfs#198]
Hi,

I am running kafka connect(HDFS connector) with version 3.2.1
Everything is working fine, I mean successfully write to HDFS location(including log and files). But, it doesn't write to local offset storage file offset.storage.file.filename=/tmp/connect-offsets. It doesn't create file connect-offsets automatically. Also, if I manually create this file, it is not written by kafka connect. So, because of this, when stop my connect and restart is again, it couldn't find the offset last time stopped. Just give some offset out of range info and then pick up from the latest offset of kafka, since I set the consumer.auto.offset.reset=latest.

Any Idea on this?
Thanks

**Comment by chengang2** [comment]
I have the same problem
how to solve the problem
