### ISSUE TITLE
Connectors don't commit if latest offset in hdfs is no longer available on topic

### ISSUE THREAD

**Issue by codenamelxl** [confluentinc/kafka-connect-hdfs#206]
My kafka connect instance crashed unnoticed for 2 hours. I have 2 connectors sinking from 2 topics. As usual, i have to manually delete the WAL in /logs before restarting Kafka connect instance.
I then noticed that both of the connectors are successfully recovered. However, one of each does not commit anything onto HDFS. Also, there is no file writtedn in /topics/+tmp/ with that topic name. After some retry, i suspect that maybe the connector is trying start from the latest offset of that topic that it found on HDFS. However, the offset is no longer available on Kafka so the connector just stuck there and trying to read from kafka over and over again.

**Comment by User1773** [comment]
I am facing the same issue. It seems that when the latest offset is  no longer available, the connector will not write any more the data, even if I have the trace: Starting commit and rotation for topic partition. It never committed into a file.

**Comment by codenamelxl** [comment]
Yeah, i think the connector should be changed so that the recovery process shouldl start at earliest or latest offset available on kafka if it can't found offset on kafka based on HDFS.

**Comment by lomignet** [comment]
This might be the fix: https://github.com/confluentinc/kafka-connect-hdfs/pull/192

**Comment by kkonstantine** [comment]
With `writeRecord` simplified we should be able to close this issue. Closing proactively here since the fix has been merged to master a few months ago and will appear in the next release of the connector (`4.0.0`).
