### ISSUE TITLE
Set username in quickstart-hdfs.properties

### ISSUE THREAD

**Issue by chenchik** [confluentinc/kafka-connect-hdfs#207]
This is probably a simple question, but how do you set the username you want connect to hdfs with?

I'm working inside of a container and using Openshift. Connect HDFS uses "root" by default since it's the user I'm logged in as. I found a workaround where I can create a new Linux user within the container and execute commands as that user, but this isn't ideal.

Is there a quick property I can set?

Something like: hdfs.username=myusername

**Comment by codenamelxl** [comment]
You can set an an environment variable named "HADOOP_USER_NAME" to the user you want. You don't have to create new Linux user with this method.
