### ISSUE TITLE
duplicate column in hive table when use partition.field.name defined in  avro schema

### ISSUE THREAD

**Issue by duke2012** [confluentinc/kafka-connect-hdfs#221]
Below items is set in quickstart-hdfs.properties file  where partition_date is a field defined in avro schema,everything is ok except this field duplicate in hive table. anyone know why? thanks in advance.

`partitioner.class=io.confluent.connect.hdfs.partitioner.FieldPartitioner
partition.field.name=partition_date`

**And hive table structure as below:**

latest_search_keyword	string              	                    
referrer            	string              	                    
referrer_host       	string              	                    
is_first_day        	boolean             	                    
is_first_time       	boolean             	                    
partition_date      	string              	                    
partition_date      	string              	                    
	 	 
Partition Information	 	 
col_name            	data_type           	comment             
partition_date      	string

**Comment by lomignet** [comment]
`partition.field.name` will add a pseudo-column named partition_date (in your example) holding the partition value. This is how Hive handles partitions. As this column already exists in your data, you end up having a duplicated column.

The solutions could be:
- choose another name for `partition.field.name`,
- choose another name in your avro schema for partition_date,
- remove partition_date from your schema if your goal was to have it filled by he connector, as it is not how it works.

**Comment by duke2012** [comment]
@lomignet  thanks ,it saves me a day.

**Comment by RussWinkler** [comment]
I know this thread is a bit old, but I'm confused by the answer here.  I was under the impression that `partition.field.name` indicated which field the Partitioner should use, not the name of the field that the Partitioner will create for partitioning.  If you choose another name for `partition.field.name` how will the Partitioner know which field in the avro schema to partition the data on?

**Comment by lomignet** [comment]
@RussWinkler You are very right. Choosing another name is relevant for a `TimebasedPartitioner` where you can specify your own field names for the different time elements via `path.format` but does not make sense for a `FieldPartitioner`.

**Comment by levzem** [comment]
closing as this solution was provided

**Comment by kkonstantine** [comment]
Fixed by: https://github.com/confluentinc/kafka-connect-hdfs/pull/526 and will appear in 10.0.0 and newer versions.
