### ISSUE TITLE
Two partitions are not processed

### ISSUE THREAD

**Issue by raju-divakaran** [confluentinc/kafka-connect-hdfs#232]
We are maintaining lot of kafka topics and many of them are sinked to HDFS using kafka connects separate for each topic.

Recently I noticed that for one topic, KC is writing data to HDFS into 14 partitions and two of the partitions are not processed. In the sense its always lagged.

I was checking the offset logs for those two partitions in HDFS and saw there isn't any data, like the content is 

`WALO=z���^O��{c���aBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINENDBEGINEND`

There are no errors in Kafka connect logs. Does anyone face similar issue and a way to troubleshoot it !?

Thanks

**Comment by ewencp** [comment]
@raju-divakaran You'd probably need to provide the raw file or a hex dump to make that WAL file decodable. All the `BEGIN``END` pairs seem a bit odd as they would normally have something in between them that would record the files being committed.

Besides errors, are there any other messages in the logs related to those topic partitions? Is it saying it is committing offsets regularly (in the HDFS connector, not the framework). You could also try turning the log level up to debug or even trace and see if that provides any more detail about what the tasks processing those partitions are actually doing.

**Comment by levzem** [comment]
closing this due to no response, but feel free to reopen if you are still having issues
