### ISSUE TITLE
Ability to rename partition column for partitioners

### ISSUE THREAD

**Issue by RussWinkler** [confluentinc/kafka-connect-hdfs#238]
When you enable hive integration with a connector and use the FieldPartitioner, it creates a new column to partition the data on with the same name as the column that are you partitioning on.  This was brought up previously in https://github.com/confluentinc/kafka-connect-hdfs/issues/221 but seems to have been satisfactorily answered by the original author.  

Our problem is that we are using Presto to connect to these hive tables and Presto chokes when there are two columns with the same name in the hive table:

`Query 20170314_185633_00138_fnxpw failed: Hive metadata for table test_table is invalid: Table descriptor contains duplicate columns`

It seems like it would be pretty easy to allow a connector parameter to let the hive metadata know what you want the partition column to be called (maybe by overloading the path.format parameter?).  At the very least add something to the column name so the partition column name isn't _exactly_ the same as the original column?

Thanks!

**Comment by GeryD** [comment]
I'm have this issue too.
From  [hive documentation](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-Create/Drop/Alter/UseDatabase) (§Partitioned Tables), field name use for partitioning should be renamed in table or should not be present

**Comment by justpresident** [comment]
The fix above is for parquet onlu, but the same problem appears for other formats as well. Specifically I have it with avro and while the table is readable by beeline client, spark 2.2.0 fails with duplicate column error.

**Comment by RussWinkler** [comment]
@GeryD and @justpresident I have fixed this issue in the most most recent versions of kafka-connect-hdfs and have opened a pull request with confluent to get it merged.  I would love to get this PR accepted before the next release so if you would please ask for it to be reviewed over there I would appreciate it!

https://github.com/confluentinc/kafka-connect-hdfs/pull/336

@justpresident I didn't know Avro was having a similar issue but you can probably follow the same format to also fix Avro!

**Comment by GeryD** [comment]
Hi @RussWinkler,
Unfortunately I'm using avro too

**Comment by Titiabackup** [comment]
Hi,

Do you know if this issue have a fix in a version ?
Thanks

**Comment by abhisheksahani** [comment]
Hi @RussWinkler  I followed your changes and made the exact same changes to ParquetHiveUtil 5.2.2 snapshot
but for me its not working can you please look at the code.

 @Override
  public void createTable(
      String database,
      String tableName,
      Schema schema,
      Partitioner partitioner
  ) throws HiveMetaStoreException {
    Table table = constructParquetTable(database, tableName, schema, partitioner);
    List<FieldSchema> columns = HiveSchemaConverter.convertSchema(schema);
    List<FieldSchema> partitions = table.getPartCols();
    
    log.info("hive create table before changes");
    for (FieldSchema partition : partitions) {
    	log.info("partition field : {} ",partition.getName());
    }
    for (FieldSchema column : columns) {
    	log.info("column field : {} ",column.getName());
    }
    
    for (FieldSchema partition : partitions) {
      for (FieldSchema column : columns) {
        if (partition.getName().equals(column.getName())) {
          columns.remove(column);
          break;
        }
      }
    }
    table.setFields(columns);
    
    
    log.info("creating hive table : {} after changes",table.toString());
    for (FieldSchema partition : table.getPartitionKeys()) {
    	log.info("partition field : {} ",partition.getName());
    }
    for(StructField field: table.getFields()) {
    	log.info("column field : {}",field.getFieldName());
    }
    hiveMetaStore.createTable(table);
  }

  @Override
  public void alterSchema(String database, String tableName, Schema schema) {
    Table table = hiveMetaStore.getTable(database, tableName);
    List<FieldSchema> columns = HiveSchemaConverter.convertSchema(schema);
    List<FieldSchema> partitions = table.getPartCols();
    
    log.info("hive alter table before changes");
    for (FieldSchema partition : partitions) {
    	log.info("partition field : {} ",partition.getName());
    }
    for (FieldSchema column : columns) {
    	log.info("column field : {} ",column.getName());
    }
    
    
    for (FieldSchema partition : partitions) {
      for (FieldSchema column : columns) {
        if (partition.getName().equals(column.getName())) {
          columns.remove(column);
          break;
        }
      }
    }
    table.setFields(columns);
    
    log.info("creating hive table : {} after changes",table.toString());
    for (FieldSchema partition : table.getPartitionKeys()) {
    	log.info("partition field : {} ",partition.getName());
    }
    for(StructField field: table.getFields()) {
    	log.info("column field : {}",field.getFieldName());
    }
    hiveMetaStore.alterTable(table);
  }

**Comment by abhisheksahani** [comment]
@RussWinkler please ignore the above comment changes are working properly thanks cheers :)

**Comment by kkonstantine** [comment]
Fixed by: https://github.com/confluentinc/kafka-connect-hdfs/pull/526 and will appear in 10.0.0 and newer versions.
