### ISSUE TITLE
Could not transfer metadata io.confluent:kafka-connect-storage-common-parent:4.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by asdf2014** [confluentinc/kafka-connect-hdfs#250]
$ mvn clean

[WARNING] Could not transfer metadata io.confluent:kafka-connect-storage-common-parent:4.1.0-SNAPSHOT/maven-metadata.xml from/to confluent (http://packages.confluent.io/maven/): Connect to packages.confluent.io:80 [packages.confluent.io/52.85.158.80, packages.confluent.io/52.85.158.222, packages.confluent.io/52.85.158.125, packages.confluent.io/52.85.158.16, packages.confluent.io/52.85.158.189, packages.confluent.io/52.85.158.247, packages.confluent.io/52.85.158.154, packages.confluent.io/52.85.158.165] failed: Connection timed out: connect

**Comment by asdf2014** [comment]
When i visited [http://packages.confluent.io/maven/io/confluent/kafka-connect-storage-common-parent/4.1.0-SNAPSHOT/maven-metadata.xml](http://packages.confluent.io/maven/io/confluent/kafka-connect-storage-common-parent/4.1.0-SNAPSHOT/maven-metadata.xml), then i got this...

![image](https://user-images.githubusercontent.com/8108788/32087300-74c0b798-bb0d-11e7-94b9-3a5ea472b3e7.png)

**Comment by kkonstantine** [comment]
You'll need since branch 4.0 to build and install [kafka-connect-storage-common](https://github.com/confluentinc/kafka-connect-storage-common) as well. 

I updated the FAQ here: https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ
to reflect this requirement.

**Comment by asdf2014** [comment]
Hi @kkonstantine . It's so helpful. Thx.
