### ISSUE TITLE
connector not on the classpath

### ISSUE THREAD

**Issue by avnerl** [confluentinc/kafka-connect-hdfs#260]
using new official open source connector version 4.0.0 taken from here: https://www.confluent.io/download/ 
tar.gz package installed inside docker image started this way:

``
connect-distributed /etc/my-connect/kafka-connect.properties
``

this is what I get when I post a new connector using curl:

```
{
  "error_code": 500,
  "message": "Failed to find any class that implements Connector and which name matches io.confluent.connect.hdfs.HdfsSinkConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}"
}
```

connector json (partial):
```
{ 
...
"connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
...
}
```

I see you removed the plugin classpath loading segment in `connect-distributed`.

**Comment by kkonstantine** [comment]
When using Confluent's docker images you now need to include the `plugin.path` as an environment variable when you start Connect's docker container (since version 4.0.0). 

For example, add: `-e CONNECT_PLUGIN_PATH=/usr/share/java`

A complete example is presented in the [quickstart](https://docs.confluent.io/current/installation/docker/docs/quickstart.html#kafka-connect)

**Comment by avnerl** [comment]
thanks for the answer. this solved my issue but now I'm facing https://github.com/confluentinc/kafka-connect-hdfs/issues/261 too.

had to hack this (since I don't need hive):

```
mv /usr/share/java/kafka-connect-storage-common/hive-exec-1.2.2.jar /tmp/
export CLASSPATH="/etc/kafka-connect/jars/*"
exec connect-distributed $BASEDIR/kafka-connect.properties
```

also please note that your [configuring-connect-with-external-jars](https://docs.confluent.io/current/installation/docker/docs/operations/external-volumes.html#configuring-connect-with-external-jars) documentation is misleading.

Confluent platform doesn't load external jars from `/etc/kafka-connect/jars/` - you need to explicitly add the path to the CLASSPATH (line 2 in my example).

**Comment by cricket007** [comment]
> you need to explicitly add the path to the CLASSPATH

As of 4.0.0, the plugin path is how to load JAR files, although the CLASSPATH will still work

**Comment by rhauch** [comment]
I'm going to close this, per the previous comments. If you still believe this is an issue, please reopen to discuss.

**Comment by avnerl** [comment]
no problem.
