### ISSUE TITLE
use regex to match topics

### ISSUE THREAD

**Issue by yuancheng-p** [confluentinc/kafka-connect-hdfs#265]
We have hundreds of kafka topics that need to be streamed to the hdfs. With the current hdfs connector, we need to declare them one by one and finally it will be a very long list. Beside that, each time when there's a new topic being added. we need to stop the connector, add it to the topic list and restart it.

My proposal is to support regex for the topics that will be streamed by hdfs connector.
For example, : `"topics":"inventory.*,history.*"` will stream all the topics with names that are started by `inventory` and `history`.

This kind of feature will help to a lot to scale up the hdfs connector.

**Comment by rhauch** [comment]
This has already been proposed, adopted, and implemented in Apache Kafka's Connect API (see [KIP-215](https://cwiki.apache.org/confluence/display/KAFKA/KIP-215%3A+Add+topic+regex+support+for+Connect+sinks)), and will be available in Apache Kafka 1.1 and Confluent Platform 4.1.
