### ISSUE TITLE
How to set the 'format.class' to the text format?

### ISSUE THREAD

**Issue by jackyoh** [confluentinc/kafka-connect-hdfs#267]
The HDFS Sink connector 'format.class' the default is Avro format, I did not find how to setting
the 'format.class' to the text file.

I want to the origin data write to the HDFS file.

Thank you.

**Comment by cricket007** [comment]
Have you tried using JSON format? 

A plain string is a valid JSON type.

**Comment by jackyoh** [comment]
Thank you for your reply.

I have tried the JSON format, but output to HDFS data is different from the origin data.
#### Example：
**Below is origin data:**
AAAA,BBBB,CCC,DDD,EEE,FFFF

**Below is output to HDFS data:**
"AAAA,BBBB,CCC,DDD,EEE,FFFF"

**Comment by cricket007** [comment]
Okay, that makes sense... 

Unfortunately, the source formats here only seem to be [Avro, Parquet, and JSON](https://github.com/confluentinc/kafka-connect-hdfs/tree/master/src/main/java/io/confluent/connect/hdfs). 

If you would like a plain-text formatter, PR's are welcome. **Note**: Personally, I feel that feature would be best placed in the [connect-storage-common](https://github.com/confluentinc/kafka-connect-storage-common) project to benefit HDFS and other FileSystems.

**Comment by jackyoh** [comment]
Yes, I see. 
Thanks for your suggestion.

**Comment by alexnu** [comment]
Just opened a PR #283 with a plain string formatter, that we developed for our needs.

I tried placing it in the connect-storage-common project as @cricket007 suggested, but I couldn't because it was dependent on hadoop configuration.

**Comment by kkonstantine** [comment]
Closing here given that the above PR has been merged and `StringFormat` is now available in the connector.

**Comment by jamessonglin** [comment]
To ingest raw json message from Kafka Topic to hadoop hdfs through hdfs connector without schema and any conversion, below are the configurations put in worker properties file and connector properties file. It worked.

Worker properties file: 
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schema.registry.url=
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schema.registry.url=
key.converter.schemas.enable=false
value.converter.schemas.enable=false

Connector properties file:
format.class=io.confluent.connect.hdfs.json.JsonFormat
