### ISSUE TITLE
Dose the connector support different flush sizes for multiple topics?

### ISSUE THREAD

**Issue by hwiceberg** [confluentinc/kafka-connect-hdfs#276]
Suppose I have topics 1 which has a data stream at 100k/s while topic 2 has a data stream at 1k/s, if I set a flush size that matches the rate of topic1, the write for topic 2 will be delayed. Can we set different flush sizes for these two topics?

**Comment by alexnu** [comment]
Hi @hwiceberg, I was facing the same issue, but then I realised you can also configure the intervals of file commits with `rotate.interval.ms` or `rotate.schedule.interval.ms`. Take a look at the [configuration options](https://docs.confluent.io/current/connect/connect-storage-cloud/kafka-connect-s3/docs/configuration_options.html).

**Comment by cricket007** [comment]
> different flush sizes for these two topics

Rather than `"topics": "topic1, topic2"`, you should `POST` two different HDFS connectors. Change all the configs you need to

**Comment by reddy1947** [comment]
what if I want to write the streaming data based on the size rather then the record count?

**Comment by cyrusv** [comment]
Currently unsupported. The best you can do is estimate based on average
record size.

If you want each topic to have different configurations, you should use
multiple connector instances
