### ISSUE TITLE
No dependency information available

### ISSUE THREAD

**Issue by binays** [confluentinc/kafka-connect-hdfs#28]
When I try to build the source, I run into the following error:

[ERROR] Failed to execute goal on project kafka-connect-hdfs: Could not resolve dependencies for project io.confluent:kafka-connect-hdfs:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: io.confluent:kafka-connect-avro-converter:jar:2.0.0-SNAPSHOT, io.confluent:common-config:jar:2.0.0-SNAPSHOT: Could not find artifact io.confluent:kafka-connect-avro-converter:jar:2.0.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/)

**Comment by ewencp** [comment]
You need to build some packages that this repository depends on. You can find them in confluentinc/schema-registry and confluentinc/common. You should `mvn install` those before building this project.

**Comment by eamocanu** [comment]
Can you explain why that is necessary? I thought maven is supposed to pull down dependencies.
