### ISSUE TITLE
how to custom hdfs filename?

### ISSUE THREAD

**Issue by guozhonghui** [confluentinc/kafka-connect-hdfs#285]
thanks for your reply!

**Comment by cricket007** [comment]
Do you have an example? What more would you need than `<topic>+<partition>+<offset>`?

**Comment by levzem** [comment]
@guozhonghui we have added some new configurations that allow customizing the `topics.dir` a bit more but we do not support customizing the actual file name. I will close this but feel free to reopen if you have follow up questions.
