### ISSUE TITLE
HA HDFS Configuration

### ISSUE THREAD

**Issue by prasanna1433** [confluentinc/kafka-connect-hdfs#288]
We are using HA HDFS cluster with two namenodes and hence we need to configure the connector in HA HDFS mode but for some reason we are able to see the kafka commits offsets in the connector logs but data is not written into the HDFS? Hash any one faces the same issue ?

I have dfs.nameservices configuration in hdfs-site.xml and other configuration for HA HDFS.

**Comment by cricket007** [comment]
I've found this is minimal set of configurations for HA HDFS to work. 

Connector properties

```json
    "hdfs.url": "hdfs://bigdata",
    "hadoop.conf.dir": "/etc/hadoop",
```

`/etc/hadoop/hdfs-site.xml`

```xml
<configuration>

    <property>
        <name>dfs.ha.automatic-failover.enabled</name>
        <value>true</value>
    </property>

    <property>
        <name>dfs.nameservices</name>
        <value>bigdata</value>
    </property>

    <property>
        <name>dfs.client.failover.proxy.provider.bigdata</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
    </property>

    <property>
        <name>dfs.ha.namenodes.bigdata</name>
        <value>nn1,nn2</value>
    </property>

    <property>
        <name>dfs.namenode.rpc-address.bigdata.nn1</name>
        <value>namenode1.fqdn:8020</value>
    </property>

    <property>
        <name>dfs.namenode.rpc-address.bigdata.nn2</name>
        <value>namenode2.fqdn:8020</value>
    </property>

</configuration>
```

**Comment by cricket007** [comment]
HDFS Connect has a write ahead log that it saves to your configured `"logs.dir"` in the connector. You might want to see if data is there until it is moved under `"topics.dir"`

**Comment by prasanna1433** [comment]
@cricket007 : Thanks for the information. I checked the configuration and all the mentioned properties are there. Now its writing into HDFS, we are using 3.2.x version and have to give "hdfs.url": "bigdata" to make it work.
Then when the "topic.dir":"first/second" the messages are written into "bigdata/first/second/kafkatopicname" folder in HDFS. Is this the expected behavior ?

**Comment by cricket007** [comment]
You can rename the nameservice to whatever you prefer, but that sounds like the correct behavior to me, yes.

**Comment by prasanna1433** [comment]
Thanks for helping me out @cricket007. It was helpful to me.
