### ISSUE TITLE
During the NameNode Switch or restart of the connector after a few hours data is left in /+tmp folder

### ISSUE THREAD

**Issue by prasanna1433** [confluentinc/kafka-connect-hdfs#289]
Hi Team,

We are using 3.2.x HDFS Sink Connector. But we are facing some problems when there is a NameNode switch or when the connectors are down for few hours. The issue is that data in the /+tmp/ folder is not getting moved the actual folder rather is left along in the /+tmp/ folder after the restart. Has anyone faces the same issue we have used both fluze.size and rotate.interval.ms properties.

Best Regards,
Prasanna Subburaj

**Comment by prasanna1433** [comment]
@cotedm @cricket007 Can you please help me with this issue.

**Comment by cricket007** [comment]
All I know is that data will temporarily exist in that location, and it'll periodically be moved into the final destination upon some condition. From what I have observed from running connect, is that having namenode HA doesn't affect that process.

**Comment by prasanna1433** [comment]
Thanks @cricket007 , I figured that even though the files are left in /+tmp/ folder the HDFS Connector is picking from the last offset where it left for each partition. So this is not an issue.
