### ISSUE TITLE
HdfsSinkConnector can not stop 

### ISSUE THREAD

**Issue by xhmz** [confluentinc/kafka-connect-hdfs#291]
kafka-connect-hdfs/src/main/java/io/confluent/connect/hdfs/HdfsSinkConnector.java
the stop Not Implemented
@Override
  public void stop() throws ConnectException {

  }

**Comment by levzem** [comment]
The actual implementation for `stop()` matters on the Task level and not the connector level. A unit of work is measured by tasks and they are the ones that have all the open resources.

https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/HdfsSinkTask.java#L165-L170

Closing this for now, but if you have any further questions please feel free to reopen.
