### ISSUE TITLE
how to import csv file from remote machine to kafka topics

### ISSUE THREAD

**Issue by hema126** [confluentinc/kafka-connect-hdfs#292]
Hi,
I have create topics in kafka, and i have to load the data from remote machine where its having huge csv data. how can i load to topic in kafka ?please explain the steps.
and also is there any time interval to load ?

**Comment by cricket007** [comment]
@hema126 Your question seems unrelated to HDFS Connect. 

Please try to use https://github.com/jcustenborder/kafka-connect-spooldir

**Comment by levzem** [comment]
closing this as this is not related to HDFS
