### ISSUE TITLE
How to read from two kafka topics with hive integration?

### ISSUE THREAD

**Issue by praneethh** [confluentinc/kafka-connect-hdfs#295]
We have deployed connector to read from one topic and load into hdfs with hive integration. Now we have a usecase to read from 2 different topics, so I gave two topics in the topics parameter with comma separated. I can see that connector is able to create two separate folders with topic names but hive external table is unable to read since there are two different directories now. What changes do I need to make so that both topics data goes into same hive table. Any ideas to resolve this issue will be helpful. @cricket007 @ewencp

**Comment by cricket007** [comment]
> both topics data goes into same hive table

That's not how it works, unfortunately. 

I would suggest you join the topics upstream, or create a Hive view that unions the tables downstream

**Comment by praneethh** [comment]
thanks

**Comment by cricket007** [comment]
@praneethh If your topic names are similar you can route both to the same hive [as mentioned in this comment](https://github.com/confluentinc/kafka-connect-hdfs/issues/189#issuecomment-298470155)

**Comment by praneethh** [comment]
thanks @cricket007 the two topics have few characters in common, I will look into the RegexpRouter and leverage in this use case
