### ISSUE TITLE
auto.offset.reset not working for compacted topic

### ISSUE THREAD

**Issue by praneethh** [confluentinc/kafka-connect-hdfs#308]
I have a compacted topic and wanted to read from latest offset so I modified the auto.offset.reset=latest in connect-distributed-worker.properties file. When I restarted the connector(with new group.id) I can see the property changes in the log but the connector is still fetching the messages from beginning. Am I missing something here? Any suggestions to read from latest offset will be helpful @cricket007 @ewencp

**Comment by cricket007** [comment]
https://stackoverflow.com/questions/49837808/camus-migration-kafka-hdfs-connect-does-not-start-from-the-set-offset

**Comment by kkonstantine** [comment]
See related issue: https://github.com/confluentinc/kafka-connect-hdfs/issues/127
I as mention there, after PR: https://github.com/confluentinc/kafka-connect-hdfs/pull/305 you have a few more options available in order to reset offsets if there are no files in HDFS
