### ISSUE TITLE
Failed to build from source

### ISSUE THREAD

**Issue by lnquy** [confluentinc/kafka-connect-hdfs#311]
Hi all,
I tried to build from source code of 4.0.0 release but there're two problems in `pom.xml` file which still remained in HEAD.  
I noticed these two problems already reported in [schema-registry](https://github.com/confluentinc/schema-registry/issues/630) but not on this repo so I just put it here.  

1. Maven failed to resolve the `confluent.maven.repo` property for Confluent repository's URL.
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:rest-utils-parent:[unknown-version]: Could not transfer artifact io.confluent:common:pom:4.0.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 8, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.confluent:rest-utils-parent:[unknown-version] (/home/lnquy/workspace/projects/java/rest-utils/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:rest-utils-parent:[unknown-version]: Could not transfer artifact io.confluent:common:pom:4.0.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 8, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
```

2. Missing Confluent repository for plugins cause failed to find io.confluent:build-tools:jar.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project kafka-connect-hdfs: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Failure to find io.confluent:build-tools:jar:4.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**>> FIX**
```
$ git diff
diff --git a/pom.xml b/pom.xml
index cb0e27e..5ca08c5 100644
--- a/pom.xml
+++ b/pom.xml
@@ -63,10 +63,18 @@
         <repository>
             <id>confluent</id>
             <name>Confluent</name>
-            <url>${confluent.maven.repo}</url>
+            <url>http://packages.confluent.io/maven/</url>
         </repository>
     </repositories>
 
+    <pluginRepositories>
+        <pluginRepository>
+            <id>confluent</id>
+            <name>Confluent</name>
+            <url>http://packages.confluent.io/maven/</url>
+        </pluginRepository>
+    </pluginRepositories>
+    
     <dependencyManagement>
         <dependencies>
             <dependency>
```

**Comment by cricket007** [comment]
Why can't you do `mvn clean install -Dconfluent.maven.repo= http://packages.confluent.io/maven`?

**Comment by dsvikas** [comment]
I am facing a similar error. I tried the option of adding plugin repository but it did not work, Can anyone please help here? The error is:
Project build error: Non-resolvable parent POM for io.confluent:kafka-connect-hdfs:[unknown-version]: Failure to transfer io.confluent:kafka-connect-storage-common-parent:pom:5.0.0-SNAPSHOT from ${confluent.maven.repo} was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced. Original error: Could not transfer artifact io.confluent:kafka-connect-storage-common-parent:pom:5.0.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM	pom.xml	/kafka-connect-hdfs-master	line 23	Maven pom Loading Problem

**Comment by cricket007** [comment]
@dsvikas https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ

**Comment by koertkuipers** [comment]
instead of workaround like `-Dconfluent.maven.repo=https://packages.confluent.io/maven` why can we not make these projects so that they simply work?

**Comment by koertkuipers** [comment]
@cricket007 are you suggesting its the parent pom that needs to be fixed?
best, koert

**Comment by cricket007** [comment]
Yes, however, it appears to me it's already there (just not https)

**Comment by kkonstantine** [comment]
We don't publish snapshot version to a public maven repo. For development on a snapshot version, (e.g. `master` or a release branch such as `5.0.x`, etc) please follow the instructions in the [FAQ](https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ) and checkout and build all the confluent project that HDFS connector has as dependencies (even transitive deps).

**Comment by eneveu** [comment]
> opment on a snapshot version, (e.g. `master` or a release branch such as `5.0.x`, etc) please follow the instructions in the [FAQ](https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ) and checkout and build all the confluent project that HDFS connector has as dependencies (even transitive deps).

I just had a similar problem as the original poster. The problem is not related to building a snapshot version, since we are building a stable version (v5.1.2 in my case). The problem is that Maven doesn't seem to do property interpolation for the repository url. I fixed it by doing something similar to @lnquy :

```
diff --git a/pom.xml b/pom.xml
index d8ebee0..701e7b1 100644
--- a/pom.xml
+++ b/pom.xml
@@ -45,7 +45,6 @@
     </modules>

     <properties>
-        <confluent.maven.repo>http://packages.confluent.io/maven/</confluent.maven.repo>
         <log4j.version>1.7.25</log4j.version>
         <checkstyle.suppressions.location>checkstyle/suppressions.xml</checkstyle.suppressions.location>
     </properties>
@@ -54,7 +53,7 @@
         <repository>
             <id>confluent</id>
             <name>Confluent</name>
-            <url>${confluent.maven.repo}</url>
+            <url>http://packages.confluent.io/maven/</url>
         </repository>
     </repositories>
```

With this change, Maven correctly download dependencies and builds my project.

Seems to be related to this : http://maven.40175.n5.nabble.com/Settings-properties-not-resolved-when-used-in-repository-element-td5746974.html
