### ISSUE TITLE
AvroData is initialized without configuration

### ISSUE THREAD

**Issue by dcsobral** [confluentinc/kafka-connect-hdfs#326]
On `AvroFormat` and a couple of other places, `AvroData` is instantiated with a sole hard-coded cache size parameter, ignoring the other `AvroDataConfig` parameters. In particular, the absence of `ENHANCED_AVRO_SCHEMA_SUPPORT_CONFIG` can prevent it from encoding the data generated by `AvroConverter`.

To compound this, `StorageSinkConnectorConfig`, and, therefore, `HdfsSinkConnectorConfig`, actually has a method that returns `AvroDataConfig`, so code to just pass all its parameters is shorter than what is being done right now.

**Comment by ls12styler** [comment]
Is there any chance that this issue will be fixed? It's been open 2 years and I'm suffering from an issue that would seem to be resolved by this (i.e the `enhanced.avro.schema.support` config setting at worker/connector level is not passed into AvroDataConfig, meaning that Enums are converted to strings in HDFS and we are required to preserve the type).
