### ISSUE TITLE
kafka-connect hdfs doesn't work with azure data lake 

### ISSUE THREAD

**Issue by imjksingh** [confluentinc/kafka-connect-hdfs#333]
i tries using kafka-connect-hdfs for azure data lake since it is compatible with HDFS API.
However it doesn't seem to work and gives following error
`"java.lang.NullPointerException\n\tat io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:135)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:377)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:576)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)\n",`

My connector properties are as follows:

`{
  "name": "adl-sink",
  "config": {
    "hadooo.home":"/usr/hdp/2.6.0.3-8/hadoop",
    "hadoop.conf.dir":"/etc/hadoop/conf",
    "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
    "tasks.max": "1",
    "topics": "adl-test",
    "hdfs.url": "adl://ADL.azuredatalakestore.net",
    "flush.size": "3",
    "name": "adl-sink"
  }
}
`

**Comment by ppizarro** [comment]
I I tried adding the azure-data-lake jars the /etc/kafka-connect/jars directory but I had the same problem. Note that it can not find a FileSystem class that implements the adl protocol:
```
kafka-connect_1    | [2018-06-13 16:46:07,282] INFO Couldn't start HdfsSinkConnector: (io.confluent.connect.hdfs.HdfsSinkTask)
kafka-connect_1    | org.apache.kafka.connect.errors.ConnectException: java.lang.reflect.InvocationTargetException
kafka-connect_1    | 	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:56)
kafka-connect_1    | 	at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:213)
kafka-connect_1    | 	at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:101)
kafka-connect_1    | 	at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:82)
kafka-connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
kafka-connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
kafka-connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
kafka-connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
kafka-connect_1    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
kafka-connect_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kafka-connect_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
kafka-connect_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
kafka-connect_1    | 	at java.lang.Thread.run(Thread.java:748)
kafka-connect_1    | Caused by: java.lang.reflect.InvocationTargetException
kafka-connect_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
kafka-connect_1    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
kafka-connect_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
kafka-connect_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
kafka-connect_1    | 	at io.confluent.connect.storage.StorageFactory.createStorage(StorageFactory.java:51)
kafka-connect_1    | 	... 12 more
kafka-connect_1    | Caused by: java.io.IOException: No FileSystem for scheme: adl
kafka-connect_1    | 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
kafka-connect_1    | 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
kafka-connect_1    | 	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
kafka-connect_1    | 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
kafka-connect_1    | 	at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:2691)
kafka-connect_1    | 	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:420)
kafka-connect_1    | 	at io.confluent.connect.hdfs.storage.HdfsStorage.<init>(HdfsStorage.java:56)
kafka-connect_1    | 	... 17 more
```

**Comment by cricket007** [comment]
> Caused by: java.io.IOException: No FileSystem for scheme: adl

Might be related to [HADOOP-14205](https://issues.apache.org/jira/browse/HADOOP-14205)

And you need to [edit the `core-site.xml` in the Kafka Connector `hadoop.conf.dir` property](https://hadoop.apache.org/docs/r3.0.0-alpha2/hadoop-azure-datalake/index.html#Enabling_ADL) 

```xml
    <property>
        <name>fs.adl.impl</name>
        <value>org.apache.hadoop.fs.adl.AdlFileSystem</value>
    </property>

    <property>
        <name>fs.AbstractFileSystem.adl.impl</name>
        <value>org.apache.hadoop.fs.adl.Adl</value>
    </property>
```

**Comment by imjksingh** [comment]
I tried editing the hadoop _core-site.xml_ and added _hadoop.conf.dir=/etc/hadoop/conf_ but still it doesn't work.

**Comment by ppizarro** [comment]
@imjksingh I did the same and I still added the azure jars to the /etc/kafka-connect/jars directory, but still it doesn't work. Same exception: No FileSystem for scheme: adl

**Comment by cricket007** [comment]
Tried adding JAR into `kafka-connect-hdfs`?

**Comment by sumitbaurai** [comment]
was there ever a resolution to this question? If yes, can you please share

**Comment by sgiovinetti** [comment]
I'm also interested if you have found out a solution.

Just for your info you can call ADLS also using the URI:  swebhdfs://<instance>.azuredatalakestore.net

**Comment by tudormaz** [comment]
For the people having trouble with this:
In this Git repo, in the pom.xml we changed the following on branch 3.2.2: 
<hadoop.version>2.9.0</hadoop.version> 

Also, this dependency is required 
```
<dependency> 
  <groupId>org.apache.hadoop</groupId> 
  <artifactId>hadoop-azure-datalake</artifactId> 
  <version>${hadoop.version}</version> 
</dependency>
<dependency>
  <groupId>org.apache.hadoop</groupId>
  <artifactId>hadoop-azure</artifactId>
  <version>${hadoop.version}</version>
</dependency>
```

Then, standard configuration defined in core-site.xml 
_/<path-to-core-site.xml-parent-folder>/core-site.xml_ 
E.g. /opt/datalake/core-site.xml

```
<?xml version="1.0"?> 
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration> 
  <property> 
    <name>fs.adl.oauth2.access.token.provider.type</name> 
    <value>ClientCredential</value> 
  </property>

  <property> 
    <name>fs.adl.oauth2.refresh.url</name> 
    <value>https://login.microsoftonline.com/[tenant-ID]/oauth2/token</value> 
  </property>

  <property> 
    <name>fs.adl.oauth2.client.id</name> 
    <value>[Application ID]</value> 
  </property>

  <property> 
    <name>fs.adl.oauth2.credential</name> 
    <value>[Application Secret]</value> 
  </property> 
  <property> 
    <name>fs.adl.impl</name> 
    <value>org.apache.hadoop.fs.adl.AdlFileSystem</value> 
  </property> 
  <property> 
    <name>fs.AbstractFileSystem.adl.impl</name> 
    <value>org.apache.hadoop.fs.adl.Adl</value> 
  </property>

</configuration>
```

And 
/opt/confluent/etc/kafka-connect-hdfs/azure-datalake-hdfs-sink.json 
```
{ 
  "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector", 
  "name": "azure-datalake-hdfs-sink", 
  "topics": "<topic>", 
  "hdfs.url": "adl://<datalake-instance>.azuredatalakestore.net", 
  "hdfs.authentication.kerberos": "false", 
  "flush.size": "1", 
  "hadoop.conf.dir": "/<path-to-core-site.xml-parent-folder>" // E.g /opt/datalake/core-site.xml 
}
```

Hope this helps.

**Comment by cricket007** [comment]
You should only need the JAR files, as mentioned. The Hadoop version shouldn't need altered. 

First, https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-azure/2.7.3

Then, Hortonworks backported these for Hadoop 2.7.3, mentioned in the POM

https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-azure-datalake/2.7.3.2.6.5.3000-28

And that has a dependency on
https://mvnrepository.com/artifact/com.microsoft.azure/azure-data-lake-store-sdk/2.2.5

**Comment by awebneck** [comment]
I still seem to be having an issue in that the Hortonworks backport version noted above is attempting to call a method that isn't *present* in hadoop-common 2.7.3 - namely `org.apache.hadoop.conf.Configuration.reloadExistingConfigurations`.

**Comment by awebneck** [comment]
I managed to track the versions of the `hadoop-azure-datalake` lib back to one that didn't attempt to call the above nonexistent method (these methods weren't added to `hadoop-common` until version 2.8.0), and succeeded for that one; but there is yet another definitely-not-in-2.7.3 method in that library that still fails to work correctly, and it's being called as far back as the versions go. Suspect that we may need a different backport that *isn't* a Hortonworks one.

**Comment by awebneck** [comment]
I have branched off the original `hadoop-azure-datalake` library and backported myself to the confirmed version of `hadoop` v2.7.3 used by the HDFS connector. It's still very much in alpha mode, and it isn't the prettiest code I've ever written, but I can confirm it works. https://github.com/rentpath/hadoop-azure-datalake https://oss.sonatype.org/content/repositories/snapshots/com/rentpath/hadoop-azure-datalake/2.7.3-0.1.0-SNAPSHOT/

**Comment by aakashnshah** [comment]
There are separate Azure Data Lake Storage Gen 1 and 2 connectors on Confluent Hub now. Closing this issue as that should resolve the problem.
