### ISSUE TITLE
the start-end offset in file name doesn’t match the flush size

### ISSUE THREAD

**Issue by snehamj** [confluentinc/kafka-connect-hdfs#334]
We're using confluent-4.0.0 for running hdfs connector in distributed mode with 12 tasks (topic has 12 partitions). These are the values of my connector:
```
        connect.hdfs.keytab =
	connect.hdfs.principal =
	filename.offset.zero.pad.width = 10
	flush.size = 1000
	format.class = class io.confluent.connect.hdfs.avro.AvroFormat
	hadoop.conf.dir =
	hadoop.home =
	hdfs.authentication.kerberos = false
	hdfs.namenode.principal =
	hdfs.url = maprfs://test/
	kerberos.ticket.renew.period.ms = 3600000
	logs.dir = logs
	retry.backoff.ms = 5000
	rotate.interval.ms = 60000
	rotate.schedule.interval.ms = -1
	schema.cache.size = 1000
	schema.registry.url = http://localhost:8081
	shutdown.timeout.ms = 3000
```

Though the flush size is 1000, there are few hdfs files with more than 1000 records ACCORDING to the filename:
`INFO Committed maprfs://test/test.output/partition=8/test.output+8+0002002891+0002003895.avro for test.output-8 (io.confluent.connect.hdfs.TopicPartitionWriter:752)`

BUT when I run avro java jar on this ^ file and look for the number of lines, it's 1000. So that is correct but the offsets in the file name are wrong!

**Comment by User1773** [comment]
Hi,
A possible explanation is that some records are lost because of the retention policy defined for the topic, Then in such case the offset (which is always increasing) is no longer equal of the number of records in the data file.

**Comment by kkonstantine** [comment]
Exactly. You might be exporting a compacted topic for instance. 

Closing the issue since it does not apply.
