### ISSUE TITLE
Failed to build from source 

### ISSUE THREAD

**Issue by vutbao** [confluentinc/kafka-connect-hdfs#376]
Hello There,
I'm trying to build kafka-connect-hdfs and get the below errors.  I'm not sure how to resolve this.

Thanks,

[INFO] ------------------------------------------------------------------------
[INFO] Building kafka-connect-hdfs 5.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://artifactory...com/artifactory/repo/io/confluent/kafka-connect-packaging-plugins/0.10.0/kafka-connect-packaging-plugins-0.10.0.pom
Downloading: https://artifactory...com/artifactory/repo/io/confluent/kafka-connect-packaging-plugins/0.10.0/kafka-connect-packaging-plugins-0.10.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.171 s
[INFO] Finished at: 2018-09-28T11:45:10-07:00
[INFO] Final Memory: 14M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin io.confluent:kafka-connect-maven-plugin:0.10.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for io.confluent:kafka-connect-maven-plugin:jar:0.10.0: Could not transfer artifact io.confluent:kafka-connect-packaging-plugins:pom:0.10.0 from/to central (https://artifactory...com/artifactory/repo): Failed to transfer file: https://artifactory...com/artifactory/repo/io/confluent/kafka-connect-packaging-plugins/0.10.0/kafka-connect-packaging-plugins-0.10.0.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by levzem** [comment]
closing because answered
