### ISSUE TITLE
Class io.confluent.connect.hdfs.string.StringFormat could not be found

### ISSUE THREAD

**Issue by rajilion** [confluentinc/kafka-connect-hdfs#392]
Hi i am trying to move csv data from kafka to hdfs using hdfs sink connector and below are the properties i used

**Connect.properties**

name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
format.class=io.confluent.connect.hdfs.string.StringFormat
tasks.max=1
topics=topic_name
hadoop.conf.dir=/etc/hadoop/conf
hdfs.url=hdfs://nameservice1/dir
flush.size=3
hdfs.authentication.kerberos=true
connect.hdfs.principal=principal
connect.hdfs.keytab=principal.keytab
hdfs.namenode.principal=principal
partitioner.class=io.confluent.connect.hdfs.partitioner.TimeBasedPartitioner
partition.duration.ms=300000
path.format=path.format='year'=YYYY/'month'=MM/'day'=dd
locale=en
timezone=EST

**worker properties**
bootstrap.servers=kafkaserver
plugin.path=/opt/confluent/share/java
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
offset.storage.file.filename=/tmp/connect.offsets
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
consumer.group.id=connect_group
consumer.auto.offset.reset=earliest

and i use **confluent-5.0.1**

but i get the below exception when i run kafka connect

java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value io.confluent.connect.hdfs.string.StringFormat for configuration format.class: Class io.confluent.connect.hdfs.string.StringFormat could not be found.
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:110)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value io.confluent.connect.hdfs.string.StringFormat for configuration format.class: Class io.confluent.connect.hdfs.string.StringFormat could not be found.
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at org.apache.kafka.connect.runtime.AbstractHerder.maybeAddConfigErrors(AbstractHerder.java:423)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:189)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:107)

**Comment by Ihabamer** [comment]
Could be the :
path.format=path.format='year'=YYYY/'month'=MM/'day'=dd
It should be :
path.format='year'=YYYY/'month'=MM/'day'=dd

**Comment by kaushiksrinivas** [comment]
Any updates on this issue ?

**Comment by jamessonglin** [comment]
I'm using confluent 3.3 community version hdfs connector and have same issue. Can someone tell from which confluent version the StringFormat is supported? My requirement is simple to consume json message (no schema) from Kafka and ingest into hdfs as a file that have json document in it.

**Comment by kkonstantine** [comment]
@jamessonglin for each connector we publish the release notes on its documentation page. Here that would be: 
https://docs.confluent.io/kafka-connect-hdfs/current/changelog.html

You may read there that this formatter was added with version `4.1.0` of the connector. You can download this or a newer version from the connector's page in Confluent Hub: https://www.confluent.io/hub/confluentinc/kafka-connect-hdfs

(of course changes and association with a certain version can be extracted from the git repo itself as well).
