### ISSUE TITLE
directory path concatenates by default the topic name

### ISSUE THREAD

**Issue by aminejamoussi** [confluentinc/kafka-connect-hdfs#404]
I noticed that the topicname is concatenated to the "topics.dir" value, is there anyway to not do concatenation for that ?

example : 

"topics.dir": "/lake/bddf/aaa/cro",
"topics": "bddfskcdev2cro",

==> the path of file are : "/lake/bddf/aaa/cro/bddfskcdev2cro"    and I want it to be only "/lake/bddf/aaa/cro/"

**Comment by cricket007** [comment]
Out of the box, no. 

You would have to write your own `Partitioner` implementation, and override the `generatePartitionedPath` method to exclude the topic name.

**Comment by aminejamoussi** [comment]
ok thanks.

**Comment by cricket007** [comment]
For reference, the source implementation is in a separate project, not specific to HDFS, but all storage connectors. 

https://github.com/confluentinc/kafka-connect-storage-common/blob/master/partitioner/src/main/java/io/confluent/connect/storage/partitioner/DefaultPartitioner.java#L46-L54

**Comment by aminejamoussi** [comment]
OK

**Comment by zallan114** [comment]
> Out of the box, no.
> 
> You would have to write your own `Partitioner` implementation, and override the `generatePartitionedPath` method to exclude the topic name.


 I don't think this can be overrided. as I tried to override this method, but it will cause offset recover to zero always.  and this is hardcoded in a file util class.

**Comment by cricket007** [comment]
I meant the directory, not the file name

**Comment by zallan114** [comment]
yes, the directory has to contains the topic_name, if overrided in own Partitioner, it will cause offset recovery to zero.

**Comment by cricket007** [comment]
I remember being told by someone around the release of the 4.x that the offset was maintained by the offsets topic, not the filesystem anymore.

Maybe that's only for S3 Connect

**Comment by levzem** [comment]
there is no way to partition without including the topic name. Closing this, please reopen if there are further questions.

**Comment by OneCricketeer** [comment]
Yes there is... `@Override public String generatePartitionedPath`
