### ISSUE TITLE
Error:java: warnings found and -Werror specified

### ISSUE THREAD

**Issue by Viking-Bird** [confluentinc/kafka-connect-hdfs#409]
I compile the source code of 5.1.0 version of kafka-connect-hdfs and throw an Error: Java: warnings found and -werror specified exception. My idea version is 2018.3.4 and JDK version is 1.8.0_181.What is the reason?

**Comment by vijaygurunanee** [comment]
I know it is too late for this...
when i had this error, i had warnings along with errors...
Most of them were: unchecked type is passed.
When i fixed these warnings, the problem got resolved automatically.

**Comment by aakashnshah** [comment]
Hi @Viking-Bird, this is caused due to having the `-Werror` flag enabled, which treats all warnings as build errors. You can resolve this by removing the flag from compiler settings in your IDE. Closing this issue as this should resolve the issue.
