### ISSUE TITLE
Task is being killed and will not recover until manually restarted

### ISSUE THREAD

**Issue by sgulati89** [confluentinc/kafka-connect-hdfs#411]
Hi,

Hdfs sink threw null pointer  with following error message:
Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)

Cause of exception " hdfs cluster was not reachable "

Is there a way to stop/terminate kafka connect process is such exception occurs?

Confluent version:4.1.0

**Comment by rhauch** [comment]
Terminate the Connect worker process any way, either with Ctrl-C (easiest) or killing the process. Connect registers a shutdown handler to stop gracefully.

**Comment by sgulati89** [comment]
Hi Rhuach,
We are running kafka connect process in standalone mode in our prod env . I cannot ctrl+c or kill the process like that there. 

My question was "Is there a way that in case of such exceptions connector itself terminates because as the per the log message it will anyways wont recover untill manually restarted"

**Comment by cricket007** [comment]
Note that running in standalone is not really encouraged, but it still binds to the `rest.port` of the Connect API, thus you can still invoke `/pause`, `/resume`, and `/restart` HTTP endpoints to stop/start the Connector.  

> Is there a way that in case of such exceptions connector itself terminates?

Yes, as the logs will indicate, *will not recover until manually restarted*.

**Comment by darshan-ss** [comment]
> Note that running in standalone is not really encouraged, but it still binds to the `rest.port` of the Connect API, thus you can still invoke `/pause`, `/resume`, and `/restart` HTTP endpoints to stop/start the Connector.
> 
> > Is there a way that in case of such exceptions connector itself terminates?
> 
> Yes, as the logs will indicate, _will not recover until manually restarted_.

Can you please elaborate how to restart connector through rest.port automatically?

**Comment by OneCricketeer** [comment]
Nothing is automatic. Poll the status endpoint. Post to the restart endpoint. Simple Cron will work fine
