### ISSUE TITLE
HDFS FileSystem Cache Problem

### ISSUE THREAD

**Issue by HeryLong** [confluentinc/kafka-connect-hdfs#418]
Recently, I'm working on an ```ClosedChannelException``` of kafka-connect-hdfs, and I find that

1. ```WALFile.java``` have fellowing code

```
fs = filename.getFileSystem(conf);

...

log.error("Failed creating a WAL Reader: " + re.getMessage());
if (re.getClassName().equals(WALConstants.LEASE_EXCEPTION_CLASS_NAME)) {
  if (fs != null) {
    fs.close();
  }
}

```
link to [WALFile.java#L146](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/wal/WALFile.java#L146)

2. ```StringRecordWriterProvider.java``` have fellowing code

```
final OutputStream out = path.getFileSystem(conf.getHadoopConfiguration()).create(path);

...

writer.close();
```
link to [StringRecordWriterProvider.java#L64](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/string/StringRecordWriterProvider.java#L64)

So, while working under hdfs default configuration `fs.hdfs.impl.disable.cache=false`, will these code have effect to each other, such as one close HDFS FileSystem, which may lead to the other one get ```ClosedChannelException```? Or, we should set  `fs.hdfs.impl.disable.cache=true` while using this plugin always ?

Any one have some explication for this? 3ks

**Comment by cyrusv** [comment]
@HeryLong , it seems you're seeing this issue: https://github.com/confluentinc/kafka-connect-hdfs/issues/141#issuecomment-479196510

The best solution here is to upgrade HDFS. If that's not an option, then it is recommended to turn caching off in HDFS as you suggest. H

**Comment by HeryLong** [comment]
@cyrusv 
ok, got it. thank you for your comment~
