### ISSUE TITLE
要么别开元了

### ISSUE THREAD

**Issue by loveship00** [confluentinc/kafka-connect-hdfs#441]
clone下来都跑不了，还要我来给你们擦屁股

**Comment by mylittlecabin** [comment]
折腾了一天感觉是挺坑的...   也许是组织没资源下功夫搞吧

**Comment by ncliang** [comment]
Please read the [FAQ](https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ) and reopen if you still cannot build.
