### ISSUE TITLE
kafka-hdfs-connector

### ISSUE THREAD

**Issue by guping98** [confluentinc/kafka-connect-hdfs#445]
Hi 
kind of new here. Appreciate if someone can give me any help here!
I am trying to set up  kafka-hdfs connector to transfer data from kafka topics (mahchine A) to another machine (B) HDFS. 

i used  connect-avro-standalone-hdfs.properties
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081

The hdfs property file:

name=hdfs-sink
connector.class=io.confluent.connect.hdfs.HdfsSinkConnector
tasks.max=1
topics=testtopic
flush.size=3
hdfs.url=hdfs://<nameNode>:8020

It first gave me error: 
org.apache.kafka.connect.errors.ConnectException: org.apache.hadoop.security.AccessControlException: Permission denied: user=kafka, access=WRITE, inode="/":hdfs:supergroup:drwxr-xr-x

I changed my topic to be
I added:
topics.dir=/tmp
logs.dir=/tmp/logs

Now the error is:
org.apache.kafka.connect.errors.ConnectException: java.net.ConnectException: Call From <Ip1>/10.224.81.104 to <nameNode>:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
        at io.confluent.connect.hdfs.storage.HdfsStorage.exists(HdfsStorage.java:107)
        at io.confluent.connect.hdfs.DataWriter.createDir(DataWriter.java:531)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:221)
        at io.confluent.connect.hdfs.DataWriter.<init>(DataWriter.java:101)
        at io.confluent.connect.hdfs.HdfsSinkTask.start(HdfsSinkTask.java:82)

I know 8020 is not blocking. What is wrong here? Why is there connection Exception?

**Comment by ncliang** [comment]
Please try setting 'hdfs.url' to point to machine B instead of ":8020". The [quickstart](https://docs.confluent.io/current/connect/kafka-connect-hdfs/index.html#quick-start) guide is a good place to start with example configs.
