### ISSUE TITLE
Connector fails when using nested Avro schema  Caused by: org.apache.kafka.connect.errors.DataException: Standalone null schemas are not supported by this converter

### ISSUE THREAD

**Issue by abhisheksahani** [confluentinc/kafka-connect-hdfs#449]
event structure :
{
  "project": "rc",
  "name": "testEventSetToDefault",
  "tenant": "pg24",
  "group": "rc",
  "userId": 7,
  "visitorId": null,
  "systime": 1565158963956,
  "value": {
    "replaceVal1": 10000,
    "appVersion": 1,
    "amount1": 1000,
    "browser": "safari",
    "deviceModel": "xs",
    "systime": 1565158963956,
    "deviceManufacturer": "apple",
    "transactionTime": 1565090795201,
    "userId": "9219559578",
    "operatingSystem": "ios",
    "paymentGateway": "PAYTM",
    "status": true
  },
  "userProperties": {
    "rnczoa": 99999,
    "testEventSetToDefault_cnt": 3,
    "old_testEventSetToDefault_lstTrckd": 1565158963956,
    "old_testEventSetToDefault_cnt": 2,
    "old_mttpxk": 99999,
    "old_rnczoa": 99999,
    "testEventSetToDefault_lstTrckd": 1565158963956,
    "mttpxk": 99999
  }
}

avro schema 
{
  "type": "record",
  "name": "myschema",
  "fields": [
    {
      "name": "project",
      "type": "string",
      "doc": "Type inferred from '\"rc\"'"
    },
    {
      "name": "name",
      "type": "string",
      "doc": "Type inferred from '\"testEventSetToDefault\"'"
    },
    {
      "name": "tenant",
      "type": "string",
      "doc": "Type inferred from '\"pg24x7\"'"
    },
    {
      "name": "group",
      "type": "string",
      "doc": "Type inferred from '\"rc\"'"
    },
    {
      "name": "userId",
      "type": "int",
      "doc": "Type inferred from '7'"
    },
    {
      "name": "visitorId",
      "type": "null",
      "doc": "Type inferred from 'null'"
    },
    {
      "name": "systime",
      "type": "long",
      "doc": "Type inferred from '1565158963956'"
    },
    {
      "name": "value",
      "type": {
        "type": "record",
        "name": "value",
        "fields": [
          {
            "name": "replaceVal1",
            "type": "int",
            "doc": "Type inferred from '10000'"
          },
          {
            "name": "appVersion",
            "type": "int",
            "doc": "Type inferred from '1'"
          },
          {
            "name": "amount1",
            "type": "int",
            "doc": "Type inferred from '1000'"
          },
          {
            "name": "browser",
            "type": "string",
            "doc": "Type inferred from '\"safari\"'"
          },
          {
            "name": "deviceModel",
            "type": "string",
            "doc": "Type inferred from '\"xs\"'"
          },
          {
            "name": "systime",
            "type": "long",
            "doc": "Type inferred from '1565158963956'"
          },
          {
            "name": "deviceManufacturer",
            "type": "string",
            "doc": "Type inferred from '\"apple\"'"
          },
          {
            "name": "transactionTime",
            "type": "long",
            "doc": "Type inferred from '1565090795201'"
          },
          {
            "name": "userId",
            "type": "string",
            "doc": "Type inferred from '\"9219559578\"'"
          },
          {
            "name": "operatingSystem",
            "type": "string",
            "doc": "Type inferred from '\"ios\"'"
          },
          {
            "name": "paymentGateway",
            "type": "string",
            "doc": "Type inferred from '\"PAYTM\"'"
          },
          {
            "name": "status",
            "type": "boolean",
            "doc": "Type inferred from 'true'"
          }
        ]
      },
      "doc": "Type inferred from '{\"replaceVal1\":10000,\"appVersion\":1,\"amount1\":1000,\"browser\":\"safari\",\"deviceModel\":\"xs\",\"systime\":1565158963956,\"deviceManufacturer\":\"apple\",\"transactionTime\":1565090795201,\"userId\":\"9219559578\",\"operatingSystem\":\"ios\",\"paymentGateway\":\"PAYTM\",\"status\":true}'"
    },
    {
      "name": "userProperties",
      "type": {
        "type": "record",
        "name": "userProperties",
        "fields": [
          {
            "name": "rnczoa",
            "type": "int",
            "doc": "Type inferred from '99999'"
          },
          {
            "name": "testEventSetToDefault_cnt",
            "type": "int",
            "doc": "Type inferred from '3'"
          },
          {
            "name": "old_testEventSetToDefault_lstTrckd",
            "type": "long",
            "doc": "Type inferred from '1565158963956'"
          },
          {
            "name": "old_testEventSetToDefault_cnt",
            "type": "int",
            "doc": "Type inferred from '2'"
          },
          {
            "name": "old_mttpxk",
            "type": "int",
            "doc": "Type inferred from '99999'"
          },
          {
            "name": "old_rnczoa",
            "type": "int",
            "doc": "Type inferred from '99999'"
          },
          {
            "name": "testEventSetToDefault_lstTrckd",
            "type": "long",
            "doc": "Type inferred from '1565158963956'"
          },
          {
            "name": "mttpxk",
            "type": "int",
            "doc": "Type inferred from '99999'"
          }
        ]
      },
      "doc": "Type inferred from '{\"rnczoa\":99999,\"testEventSetToDefault_cnt\":3,\"old_testEventSetToDefault_lstTrckd\":1565158963956,\"old_testEventSetToDefault_cnt\":2,\"old_mttpxk\":99999,\"old_rnczoa\":99999,\"testEventSetToDefault_lstTrckd\":1565158963956,\"mttpxk\":99999}'"
    }
  ]
}

Kafka producer 
package com.games24x7.confluentkafkapoc;
import java.util.Properties;
import org.apache.avro.Schema;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericDatumReader;
import org.apache.avro.generic.GenericRecord;
import org.apache.avro.io.DatumReader;
import org.apache.avro.io.Decoder;
import org.apache.avro.io.DecoderFactory;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;
import org.kitesdk.data.spi.JsonUtil;
import io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig;
import io.confluent.kafka.serializers.KafkaAvroDeserializerConfig;
import io.confluent.kafka.serializers.KafkaAvroSerializer;

public class GenericRecordPublisher {

	public static GenericRecord fromJsonToAvro(String json, String schemastr) throws Exception {
		String schemaStr = schemastr;
		String genericRecordStr = json;
		Schema.Parser schemaParser = new Schema.Parser();
		Schema schema = schemaParser.parse(schemaStr);
		DecoderFactory decoderFactory = new DecoderFactory();
		Decoder decoder = decoderFactory.jsonDecoder(schema, genericRecordStr);
		DatumReader<GenericData.Record> reader = new GenericDatumReader(schema);
		GenericRecord genericRecord = reader.read(null, decoder);
		return genericRecord;
	}

	public static void main(String[] args) {
		try {
			
			Properties props = new Properties();
			props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "*.*.*.*:9092");
			props.put(ProducerConfig.ACKS_CONFIG, "all");
			props.put(ProducerConfig.RETRIES_CONFIG, 0);
			props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
			props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, KafkaAvroSerializer.class);
			props.put(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, "http://*.*.*.*:8081");
			//props.put(KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG, true);
						
String schema1= "{\"type\":\"record\",\"name\":\"myschema\",\"fields\":[{\"name\":\"project\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"rc\\\"'\"},{\"name\":\"name\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"testEventSetToDefault\\\"'\"},{\"name\":\"tenant\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"pg24x7\\\"'\"},{\"name\":\"group\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"rc\\\"'\"},{\"name\":\"userId\",\"type\":\"int\",\"doc\":\"Type inferred from '7'\"},{\"name\":\"visitorId\",\"type\":\"null\",\"doc\":\"Type inferred from 'null'\"},{\"name\":\"systime\",\"type\":\"long\",\"doc\":\"Type inferred from '1565158963956'\"},{\"name\":\"value\",\"type\":{\"type\":\"record\",\"name\":\"value\",\"fields\":[{\"name\":\"replaceVal1\",\"type\":\"int\",\"doc\":\"Type inferred from '10000'\"},{\"name\":\"appVersion\",\"type\":\"int\",\"doc\":\"Type inferred from '1'\"},{\"name\":\"amount1\",\"type\":\"int\",\"doc\":\"Type inferred from '1000'\"},{\"name\":\"browser\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"safari\\\"'\"},{\"name\":\"deviceModel\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"xs\\\"'\"},{\"name\":\"systime\",\"type\":\"long\",\"doc\":\"Type inferred from '1565158963956'\"},{\"name\":\"deviceManufacturer\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"apple\\\"'\"},{\"name\":\"transactionTime\",\"type\":\"long\",\"doc\":\"Type inferred from '1565090795201'\"},{\"name\":\"userId\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"9219559578\\\"'\"},{\"name\":\"operatingSystem\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"ios\\\"'\"},{\"name\":\"paymentGateway\",\"type\":\"string\",\"doc\":\"Type inferred from '\\\"PAYTM\\\"'\"},{\"name\":\"status\",\"type\":\"boolean\",\"doc\":\"Type inferred from 'true'\"}]},\"doc\":\"Type inferred from '{\\\"replaceVal1\\\":10000,\\\"appVersion\\\":1,\\\"amount1\\\":1000,\\\"browser\\\":\\\"safari\\\",\\\"deviceModel\\\":\\\"xs\\\",\\\"systime\\\":1565158963956,\\\"deviceManufacturer\\\":\\\"apple\\\",\\\"transactionTime\\\":1565090795201,\\\"userId\\\":\\\"9219559578\\\",\\\"operatingSystem\\\":\\\"ios\\\",\\\"paymentGateway\\\":\\\"PAYTM\\\",\\\"status\\\":true}'\"},{\"name\":\"userProperties\",\"type\":{\"type\":\"record\",\"name\":\"userProperties\",\"fields\":[{\"name\":\"rnczoa\",\"type\":\"int\",\"doc\":\"Type inferred from '99999'\"},{\"name\":\"testEventSetToDefault_cnt\",\"type\":\"int\",\"doc\":\"Type inferred from '3'\"},{\"name\":\"old_testEventSetToDefault_lstTrckd\",\"type\":\"long\",\"doc\":\"Type inferred from '1565158963956'\"},{\"name\":\"old_testEventSetToDefault_cnt\",\"type\":\"int\",\"doc\":\"Type inferred from '2'\"},{\"name\":\"old_mttpxk\",\"type\":\"int\",\"doc\":\"Type inferred from '99999'\"},{\"name\":\"old_rnczoa\",\"type\":\"int\",\"doc\":\"Type inferred from '99999'\"},{\"name\":\"testEventSetToDefault_lstTrckd\",\"type\":\"long\",\"doc\":\"Type inferred from '1565158963956'\"},{\"name\":\"mttpxk\",\"type\":\"int\",\"doc\":\"Type inferred from '99999'\"}]},\"doc\":\"Type inferred from '{\\\"rnczoa\\\":99999,\\\"testEventSetToDefault_cnt\\\":3,\\\"old_testEventSetToDefault_lstTrckd\\\":1565158963956,\\\"old_testEventSetToDefault_cnt\\\":2,\\\"old_mttpxk\\\":99999,\\\"old_rnczoa\\\":99999,\\\"testEventSetToDefault_lstTrckd\\\":1565158963956,\\\"mttpxk\\\":99999}'\"}]}";

String event1 = "{\"project\":\"rc\",\"name\":\"testEventSetToDefault\",\"tenant\":\"pg24x7\",\"group\":\"rc\",\"userId\":7,\"visitorId\":null,\"systime\":1565158963956,\"value\":{\"replaceVal1\":10000,\"appVersion\":1,\"amount1\":1000,\"browser\":\"safari\",\"deviceModel\":\"xs\",\"systime\":1565158963956,\"deviceManufacturer\":\"apple\",\"transactionTime\":1565090795201,\"userId\":\"9219559578\",\"operatingSystem\":\"ios\",\"paymentGateway\":\"PAYTM\",\"status\":true},\"userProperties\":{\"rnczoa\":99999,\"testEventSetToDefault_cnt\":3,\"old_testEventSetToDefault_lstTrckd\":1565158963956,\"old_testEventSetToDefault_cnt\":2,\"old_mttpxk\":99999,\"old_rnczoa\":99999,\"testEventSetToDefault_lstTrckd\":1565158963956,\"mttpxk\":99999}}";
GenericRecord avrorecord = fromJsonToAvro(event1, schema1);
final ProducerRecord<String, GenericRecord> record = new ProducerRecord<String, GenericRecord>("test18",avrorecord);
KafkaProducer<String, GenericRecord> producer = new KafkaProducer<String, GenericRecord>(props);
			for (int i = 1; i < 2; i++) {

				producer.send(record).get();
			}
		} catch (Exception e) {
			System.err.println(e);
		}

	}

}

connector config
{
    "name": "test18",
    "config": {
        "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
  "tasks.max": "10",
  "hdfs.url": "hdfs://*.*.*.*:9000",
  "hadoop.conf.dir": "/home/hadoop/hadoop/etc/hadoop/",
  "hadoop.home": "/home/hadoop/hadoop/",
  "hive.conf.dir": "/home/hadoop/apache-hive-2.3.5-bin/conf/",
  "hive.home": "/home/hadoop/apache-hive-2.3.5-bin/",
  "flush.size": "100",
  "format.class": "io.confluent.connect.hdfs.parquet.ParquetFormat",
  "hive.integration": "true",
  "hive.database": "testhdfsnew3",
  "hive.metastore.uris": "thrift://*.*.*.*:9083",
  "schema.compatibility": "BACKWARD",
  "partitioner.class": "io.confluent.connect.storage.partitioner.FieldPartitioner",
  "partition.duration.ms": "300000",
  "path.format": "'time'=YYYYMMddHHmm/",
  "rotate.interval.ms": "300000",
  "locale": "en",
  "topics": "test18",
  "partition.field.name": "project",
  "partition.field.name.with.time":"time",
  "timezone":"IST"
    }
}

Stack trace
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:487)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Standalone null schemas are not supported by this converter
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1679)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1507)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1625)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1484)
	at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:1193)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:97)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:487)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	... 13 more

**Comment by ncliang** [comment]
I suspect it is because of this:
```
"visitorId": null,
...
{
"name": "visitorId",
"type": "null",
"doc": "Type inferred from 'null'"
},
```
Try change `vistorId` type to something like ["string", "null"].

**Comment by abhisheksahani** [comment]
@ncliang Thankyou it sloved the problem .
