### ISSUE TITLE
Topics with periods should be supported. 

### ISSUE THREAD

**Issue by jcustenborder** [confluentinc/kafka-connect-hdfs#45]
Working with a customer who discovered. 

org.group.data.xxxx should be supported.

> Kafka topic naming. If you name a topic with periods for namespacing (I.e. org.group.data), the HDFS connector doesn’t like it. (https://github.com/confluentinc/kafka-connect-hdfs/blob/5b563417ce06c93c24c85b42d0cc94504aabe69e/src/main/java/io/confluent/connect/hdfs/filter/TopicPartitionCommittedFileFilter.java) Instead of assuming the second item in the array on line 37 is the partition, use the last item in the array; that might fix it.

**Comment by vikeshkhanna** [comment]
+1 

We have the same issue, due to which I opened #44
