### ISSUE TITLE
Not able compile the project . 

### ISSUE THREAD

**Issue by thiruthuvarajan** [confluentinc/kafka-connect-hdfs#452]
I am receiving following error.  It shows like kafka connect point connect hdfs3. :(
How do I now customize HDFS Connect

[WARNING] 'parent.relativePath' of POM io.confluent:kafka-connect-storage-common-parent:[unknown-version] **(C:\Users\joth9002\Downloads\Sample_Projects\kafka-connect-storage-common-master\pom.xml) points at io.confluent:kafka-connect-hdfs3 instead of io.confluent:common**, please verify your project structure @ line 23, column 13
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-storage-common-parent:[unknown-version]: Failure to find io.confluent:common:pom:5.4.0-SNAPSHOT in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 23, column 13

**Comment by ncliang** [comment]
Please read the [FAQ](https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ) and reopen if you still cannot build.
