### ISSUE TITLE
Upgrade Hadoop (HDFS) dependency to the latest version

### ISSUE THREAD

**Issue by candidtim** [confluentinc/kafka-connect-hdfs#480]
Current implementation of the connector uses HDFS (Hadoop) 2.7.3, which was released back in 2017 (to be precise: 2017-06-26). Some other libraries (additional HDFS drivers) have been upgraded since and depend on new HDFS 2 versions. As a result they cannot be easily used with current version of the connector.

Indeed, there is a new HDFS 3 connector, but does it mean that users of HDFS 2 will have the HDFS 2 version freezed? Are there plans to upgrade the HDFS dependency version to a more latest one? As of the time of this writing, latest Hadoop 2.x is 2.10, released on 2019-10-30.

**Comment by ncliang** [comment]
@candidtim I agree, Hadoop 2.7.3 is ancient and could use an update. If you would like to do the honors, I'm happy to review a PR for updating the Hadoop version to something newer.

**Comment by candidtim** [comment]
@ncliang , I would gladly create a PR, provided I would have enough knowledge to do so. As a quick test I've rebuilt locally `kafka-connect-storage-common` and `kafka-connect-hdfs` with Hadoop dependency version set to 2.10.0 in both. It works fine: all compiled, all tests pass. I still would like to run a a couple of tests with a running Kafka Connect instance, but I assume this is good start.

I didn't contribute to this project previously, so would like to do a quick check before I jump into making the PR. Are there any contribution guidelines? Also, as of the upgrade itself, should some other dependencies be reviewed with it, and is there some impact on an assembly process?

**Comment by ncliang** [comment]
@candidtim we have some system tests that we run to verify functionality. If you cut PRs in `kafka-connect-storage-common` and here to make the version bump, I can trigger the system test runs to verify they pass.

While you are at it, could you also bump Hive client to the latest version that works with 2.x? https://hive.apache.org/downloads.html#23-august-2019-release-236-available

**Comment by ncliang** [comment]
@candidtim I have created https://github.com/confluentinc/kafka-connect-storage-common/pull/123 to bump both Hadoop and Hive versions.

**Comment by candidtim** [comment]
@ncliang , thank you, and sorry - I indeed was too slow to react here. 

I understand that once it is merged in the kafka-connect-storage-common there will be needed a similar update in this repository, right?

**Comment by OneCricketeer** [comment]
The above was merged. What's the status here?

**Comment by ncliang** [comment]
As noted above, the version bump PR has landed in `master` already.
```
nliang-MBP:~/dev/kafka-connect-hdfs (master)$ mvn clean dependency:tree | grep hadoop
[INFO] |  +- org.apache.hadoop:hadoop-client:jar:2.10.0:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-hdfs-client:jar:2.10.0:compile
[INFO] |  |  \- org.apache.hadoop:hadoop-annotations:jar:2.10.0:compile
...
nliang-MBP:~/dev/kafka-connect-hdfs (master)$ mvn clean dependency:tree | grep hive
[INFO] |  +- org.apache.hive.hcatalog:hive-hcatalog-core:jar:2.3.6:compile
[INFO] |  |  +- org.apache.hive:hive-cli:jar:2.3.6:compile
[INFO] |  |  |  +- org.apache.hive:hive-serde:jar:2.3.6:compile
[INFO] |  |  |  |  +- org.apache.hive:hive-service-rpc:jar:2.3.6:compile
[INFO] |  |  |  +- org.apache.hive:hive-service:jar:2.3.6:compile
[INFO] |  |  |  |  +- org.apache.hive:hive-llap-server:jar:2.3.6:compile
...
```

I am closing this issue. Thanks, @OneCricketeer @candidtim !
