### ISSUE TITLE
log rolling problem

### ISSUE THREAD

**Issue by hwkim94** [confluentinc/kafka-connect-hdfs#482]
Hello, kafka-connect-hdfs!
I found that there is some problem with log of kafka connect

For example, 
nsp.log.2020-01-08 file has 2020-01-10 log
nsp.log.2020-01-09 file has 2020-01-09 log
nsp.log.2020-01-10 file has 2020-01-11 log
nsp.log.2020-01-11 file has 2020-01-12 log

Is there any wrong config with my log4j.properties?
Following is my log4j.properties

Thanks to your favor

```bash
log4j.rootLogger=INFO, logFile
	
log4j.appender.logFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.logFile.DatePattern='.'yyyy-MM-dd
log4j.appender.logFile.File=/home1/irteam/apps/confluent/logs/nsp.log
log4j.appender.logFile.layout=org.apache.log4j.PatternLayout
log4j.appender.logFile.layout.ConversionPattern=[%d] %p %m (%c)%n

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n

log4j.logger.org.apache.zookeeper=ERROR
log4j.logger.org.I0Itec.zkclient=ERROR
log4j.logger.org.reflections=ERROR
```

**Comment by ncliang** [comment]
@hwkim94 could it be log rotation is done based on system time in your local timezone while logs are writing times in another timezone like UTC?

You can have the timezone information written into the log file like this:
  https://stackoverflow.com/questions/9116425/apache-log4j-logging-with-specific-timezone

**Comment by hwkim94** [comment]
After restarting Kafka connect, the problem solved!
thanks!
