### ISSUE TITLE
SchemaProjectorException: Schema version required for BACKWARD compatibility

### ISSUE THREAD

**Issue by nd49782** [confluentinc/kafka-connect-hdfs#483]
when I registed connector instance:
`Caused by: java.lang.RuntimeException: org.apache.kafka.connect.errors.SchemaProjectorException: Schema version required for BACKWARD compatibility
	at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:408)
	at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:375)
	at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:127)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	... 10 more
Caused by: org.apache.kafka.connect.errors.SchemaProjectorException: Schema version required for BACKWARD compatibility
	at io.confluent.connect.storage.schema.StorageSchemaCompatibility.validateAndCheck(StorageSchemaCompatibility.java:157)
	at io.confluent.connect.storage.schema.StorageSchemaCompatibility.shouldChangeSchema(StorageSchemaCompatibility.java:320)
	at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:362)
	... 13 more
`

**connect-distributed.properties**
`
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
`

**connector instance**
{
  "name": "kafka2hdfs_public_mytable", 
  "config": {
    "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector", 
    "tasks.max": "1", 
    "topics": "mypostgre.public.mytable", 
    "store.url": "nn1", 
    "hadoop.conf.dir": "/usr/ghd/8.6.2.19-207/hadoop/conf", 
    "hadoop.home": "/mytest/mypostgre_public_mytable", 
    "flush.size": "1", 
    "format.class": "io.confluent.connect.hdfs.avro.AvroFormat", 
    "hive.integration": "true", 
    "hive.metastore.uris": "thrift://xxx:9083", 
    "hive.conf.dir": "/usr/ghd/8.6.2.19-207/hive/conf", 
    "hive.database": "my_test", 
    "schema.compatibility" : "BACKWARD"
  }
}

The reason I use JsonConverter is that I used Debezium Source to Kafka, and I didn't use Schema Registry.
If sink to HDFS and integrate with Hive, Is Schema Registry required？
If not necessary, what's wrong with the configuration?

**Comment by ncliang** [comment]
@nd49782 unfortunately, to safely evolve schemas, we must rely on Schema Registry and the versioned schemas it provides.

More about schema evolution can be found here - https://docs.confluent.io/current/schema-registry/avro.html

And, more information about Hive integration here - https://docs.confluent.io/current/connect/kafka-connect-hdfs/index.html#hive-integration

I am not too familiar with Debezium, but I believe they do support Schema Registry integration as documented here - https://debezium.io/documentation/reference/1.0/configuration/avro.html

Maybe give that a try?

**Comment by nd49782** [comment]
@ncliang thinks for your answer.
Schema Registry needs to be used with AvroConverter, right?

By the way, if I use HBase Sink Connector, is Schema Registry also required？

**Comment by ncliang** [comment]
@nd49782 with HBase connector, you should be able to write raw JSON without the need for avro or schema registry. https://docs.confluent.io/current/connect/kafka-connect-hbase/index.html#write-avro-message-values-into-apache-hbase

Even with HDFS Sink connector here, if you are not using Hive integration, you can write into HDFS JSON using JsonConverter. It is only the Hive integration that requires schema and schema evolution.

**Comment by nd49782** [comment]
@ncliang Ok, I'll try.Thank you!
