### ISSUE TITLE
HDFS sink writes to previous rolled log file

### ISSUE THREAD

**Issue by heaje** [confluentinc/kafka-connect-hdfs#490]
I have a strange situation where the HDFS sinks are logging to files that it has previously rolled.  For instance, all of my logs are configured to go to ```/var/log/kafka/connect-distributed.log```.  Once the maximum size of 1GB is met, the file rolls to ```/var/log/kafka/connect-distributed.log.1``` as expected.  The problem though is that while some (not all) logs are properly written to ```/var/log/kafka/connect-distributed.log```, other logs (not all) continue to be written to ```/var/log/kafka/connect-distributed.log.1```.

My log4j configuration is below.  I have done lots and lots of digging on why this is occuring, but references to this online are few and far between.  I did previously find a reference to this kind of issue when using ```org.apache.log4j.DailyRollingFileAppender``` and I then switched to ```org.apache.log4j.RollingFileAppender```, but the problem has persisted.

The only reference I can find to this other than what I mentioned above is at https://stackoverflow.com/questions/32826637/log4j-1-2-17-extras-logging-to-wrong-file.  This site references a conflicting version of log4j in another library.  

Any ideas what is going on here?  This problem of logs going to the wrong files is driving me crazy.

```log4j.rootLogger=INFO,file

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.File=${connect.logs.dir}/${connect.log.file}
log4j.appender.file.layout.ConversionPattern=[%d] %p %X{connector.context}%m (%c:%L)%n
log4j.appender.file.MaxFileSize=1GB
log4j.appender.file.MaxBackupIndex=3
log4j.appender.file.Append=true

log4j.logger.org.apache.zookeeper=ERROR
log4j.logger.org.I0Itec.zkclient=ERROR
log4j.logger.org.reflections=ERROR

**Comment by heaje** [comment]
I believe that I have found the fix to this.  There is some kind of bad interaction between the log4j-1.2.16.jar file included with the HDFS package and the log4j included with the Connect framework packages (I'm running 5.3.2 in both instances).  When I removed the log4j-1.2.16.jar from the where the HDFS sink was installed, this bad logging issue disappeared.

**Comment by OneCricketeer** [comment]
Those files and jars all come from upstream Apache project. Please close this issue and open a Kafka JIRA

**Comment by dosvath** [comment]
Closed issue due to being connect framework related, N/A for this HDFS connector.
