### ISSUE TITLE
Question : HDFS Connector release availability in RMP repo

### ISSUE THREAD

**Issue by RossierFl** [confluentinc/kafka-connect-hdfs#521]
Hello,

We are currently using the RPM repo https://packages.confluent.io/rpm/X.X/ to install the HDFS Connector inside a docker image. 
Since the version 5.3, it appear that the HDFS Connector is not present in them anymore. Has this method been discontinued and no further releases are expected to be present in the RPM repository ?

If so, what is now the official way of installing a connector and it's dependancies inside a Docker image (one docker image per connector type) ? it is the confluent-client CLI tool ? 
BR

**Comment by kkonstantine** [comment]
Your observation is correct @RossierFl 
On that version hdfs connector was removed from CP packaging and therefore rpm/deb packages stopped being produced. 

Indeed, the right way to include the connector to a docker image is to use `confluent-hub` cli. You may read more [here](https://docs.confluent.io/current/installation/docker/development.html#create-a-docker-image-containing-c-hub-connectors).
