### ISSUE TITLE
writeRecord wrongly considers a newer record as stale

### ISSUE THREAD

**Issue by vikeshkhanna** [confluentinc/kafka-connect-hdfs#69]
Hi,

We discovered that the `writeRecord` method in [TopicPartitionWriter:469](https://github.com/confluentinc/kafka-connect-hdfs/blob/ed85dbe9c73845b7e48d84fb04cafc2cf3e91792/src/main/java/io/confluent/connect/hdfs/TopicPartitionWriter.java#L466) considers a more recent Kafka Record as stale and drops it. We observed this when we ran Kafka Connect after a week long gap (with Kafka retention = 5 days). This led to `record.kafkaOffset() > expectedOffset`. My understanding is that all the more recent records were dropped since the aforementioned condition would always be true until `expectedOffset` is updated to the retention cutoff, which does not seem to be happening anywhere in the offset management code.

**Comment by Ishiihara** [comment]
@vikeshkhanna I think you are talking about that Kafka Connect is not running until a week later and some messages are already removed according to the retention policy. That certainly makes sense as now the expected offset is not correct anymore.  One solution will be seek to the beginning of the topics and if that is larger than the latest offset of the data in HDFS and set the offset to that.  This will make sure that the offset honors the retention policy.

**Comment by vikeshkhanna** [comment]
Yes, that is correct. Yeah, the ideal solution would be to update the expected offset in case some data has been dropped by Kafka based on its retention policy. I don't think this is implemented yet, that's why the bug.

**Comment by savulchik** [comment]
Seems like related to #132

**Comment by kkonstantine** [comment]
I believe this is not an issue anymore for the same reasons that were given for https://github.com/confluentinc/kafka-connect-hdfs/issues/132

`writeRecord` has been simplified in `TopicPartitionerWriter` and no records are dropped based on offset now.

I'll go ahead and close this issue marked as a bug as well, but again, feel free to reopen and provided any related logs if this is still an issue in the most recent versions.
