### ISSUE TITLE
File not written when partition changes

### ISSUE THREAD

**Issue by 13h3r** [confluentinc/kafka-connect-hdfs#71]
I have setup with `flush.size=100000` and `TimeBasedPartitioner` with `path.format=YYYY/MM/dd`.

For topics with small amount of messages this cause strange behavior. When partitioner found that partition should be changed it opens new file, but did not close the old one. So, I have not data until `flush.size` will be reached and unable to run some data dependent tasks like ETL and so.

Expected behavior for me is to close file when new partition started. What do you think?

**Comment by Ishiihara** [comment]
That is the current behavior. We currently closes all files under a topic partition once the flush size is reached. In case of time based partitioner, when a new file is created, the old file can be safely closed as no more data will be written to the old file. Plus, we know that at any given point of time, we only have one file open and I think we should allow triggering a file commit once that file is closed.  

One work around is to set the `flush.interval.ms` to be roughly the same value as your partition size. This ensures that the file is closed when the flush interval is reached.

**Comment by 13h3r** [comment]
@Ishiihara, do you agree that it will be good to close file when partition changed? I can provide PR

**Comment by 13h3r** [comment]
ping @Ishiihara

**Comment by levzem** [comment]
closing as this is addressed by discussion in #80 and by PR #87
