### ISSUE TITLE
readOffset is slow/expensive for large, highly partitioned tables

### ISSUE THREAD

**Issue by jingw** [confluentinc/kafka-connect-hdfs#77]
Our current setup has a `Partitioner` that routes data into `{topic}/day={...}/hour={...}/{actual data files}`. In some load testing with a 500 partition topic, we managed to DDoS HDFS's NameNode when our consumers were all recovering and calling `readOffset`. This function recursively scans the contents of the topic for each partition, performing a total of O(time \* partitions^2) work.

What do you feel would be a good solution to this?
1. Include offsets in WAL recovery: Have `wal.apply()` return the max offset, and then get rid of `resetOffsets`. The WAL interface would have to be less generic and would have to know about the file name format. If the WAL is empty then we need something else. Maybe part of WAL recovery can be a special "current offset" file.
2. Work around: Make Kafka partition the first directory in the `Partitioner` and do some magic special casing in `readOffset` and/or `fileStatusWithMaxOffset`. We could probably also assume that the latest offset isn't in an old time partition. If we do both of these tricks then total recovery cost becomes O(partitions \* constant for how far back we scan).

I'm happy to contribute a PR for this (though I imagine the work around in option 2 wouldn't be easily publishable).

Thanks!

**Comment by Ishiihara** [comment]
@jingw Thanks for reporting this. We definitely want to improve this behavior. Do you want to elaborate a bit more of your both options? We need a good design here as so that the scalability of the connector can be improved.

**Comment by jingw** [comment]
Thanks for the reply.

For (1), here's a patch I've been playing with: https://gist.github.com/jingw/5f427f09037c26a21978e299415e7d39 (not complete, not successfully tested)
The idea is that the write ahead log knows about the offsets, so we should be able to use that instead of recursively scanning HDFS.

(2) is a quick hack to reduce the scale of the problem. If I make my partitioning format partition/day/hour instead of day/hour, then each partition only needs to scan the day/hour for its own partition. Furthermore, if we're willing to assume some amount of ordering (e.g. data isn't out-of-order by more than a day), then we can assume the latest offset is in one of the day/hour directories. This approach would probably work for me, but I'm guessing it wouldn't be suitable for inclusion in your repo.

**Comment by dosvath** [comment]
Addressed by https://github.com/confluentinc/kafka-connect-hdfs/pull/556
