### ISSUE TITLE
Partition by multiple columns.

### ISSUE THREAD

**Issue by xianzhen** [confluentinc/kafka-connect-hdfs#83]
Hi
My hive table have to be partitioned by multiple columns. How about change the type of "partition.field.name" to LIST?

**Comment by Ishiihara** [comment]
@xianzhen That's a nice to have feature. However, the change involves changing the data organization in HDFS if we ends up supporting this. Are you interested in submitting a PR on this?

**Comment by doriwal** [comment]
Hi 

What is the status of this issue ? I also need to partition the data in parquet by several fields like 
"day,hour,type" 

which are inputs that i am adding to each event that I send to kafka

**Comment by ewencp** [comment]
@doriwal As @Ishiihara said, this would be a nice enhancement, but needs some code changes. We don't currently have this specific feature on our roadmap -- it hasn't been requested frequently so far -- but we'd be happy to see a PR for it.

For `TimeBasedPartitioner`, you might want to see discussion of enhancements in https://github.com/confluentinc/kafka-connect-hdfs/issues/98

**Comment by swierchola** [comment]
This feature has already been added. Issue can be closed as resolved.

@jcustenborder added multiple fields support to FieldPartitioner in [kafka-connect-storage-common#53](https://github.com/confluentinc/kafka-connect-storage-common/issues/53)

**Comment by levzem** [comment]
closing as resolved by #286
